/**
 * Localities per UK postcode district (outward code), so a sub-market can be
 * titled as a place ("Leicester · Clarendon Park") rather than a code
 * ("Leicester LE2"). The first name is the lead locality used in titles; the
 * rest appear as "also …" in subtitles and are searchable.
 *
 * Coverage: every district of the areas with live data plus the major cities
 * in `areas.ts`. A district that is not listed falls back to its code, so
 * nothing breaks when a new area starts reporting — add its districts here
 * when it does. Names follow the Royal Mail / Wikipedia postcode district
 * lists; check any entry you rely on against those before quoting it.
 */
const RAW: Record<string, string> = {
  // ── B · Birmingham ──
  B1: 'City centre, Brindleyplace',
  B2: 'City centre, New Street',
  B3: 'Colmore Row, Jewellery Quarter',
  B4: 'City centre, Aston University',
  B5: 'Digbeth, Highgate, Lee Bank',
  B6: 'Aston, Witton',
  B7: 'Nechells, Duddeston',
  B8: 'Washwood Heath, Ward End, Saltley',
  B9: 'Bordesley Green, Small Heath',
  B10: 'Small Heath, Sparkbrook',
  B11: 'Sparkhill, Tyseley',
  B12: 'Balsall Heath, Sparkbrook, Highgate',
  B13: 'Moseley, Billesley',
  B14: 'Kings Heath, Yardley Wood',
  B15: 'Edgbaston',
  B16: 'Ladywood, Five Ways, Edgbaston',
  B17: 'Harborne',
  B18: 'Jewellery Quarter, Hockley, Winson Green',
  B19: 'Lozells, Newtown',
  B20: 'Handsworth Wood, Birchfield, Perry Barr',
  B21: 'Handsworth',
  B23: 'Erdington, Short Heath',
  B24: 'Erdington, Tyburn',
  B25: 'Yardley',
  B26: 'Sheldon, Yardley',
  B27: 'Acocks Green',
  B28: 'Hall Green',
  B29: 'Selly Oak, Bournville, Weoley Castle',
  B30: 'Bournville, Stirchley, Cotteridge',
  B31: 'Northfield, Longbridge',
  B32: 'Bartley Green, Quinton, Woodgate',
  B33: 'Kitts Green, Stechford',
  B34: 'Shard End, Buckland End',
  B35: 'Castle Vale',
  B36: 'Castle Bromwich, Hodge Hill',
  B37: 'Chelmsley Wood, Marston Green',
  B38: 'Kings Norton',
  B40: 'NEC, Birmingham Airport',
  B42: 'Perry Barr, Great Barr',
  B43: 'Great Barr, Hamstead',
  B44: 'Kingstanding, Perry Barr',
  B45: 'Rednal, Rubery',
  B46: 'Coleshill, Water Orton',
  B47: 'Wythall, Hollywood',
  B48: 'Alvechurch',
  B49: 'Alcester',
  B50: 'Bidford-on-Avon',
  B60: 'Bromsgrove',
  B61: 'Bromsgrove',
  B62: 'Halesowen, Hasbury',
  B63: 'Halesowen',
  B64: 'Cradley Heath, Old Hill',
  B65: 'Rowley Regis, Blackheath',
  B66: 'Smethwick',
  B67: 'Bearwood, Smethwick',
  B68: 'Oldbury',
  B69: 'Oldbury, Tividale',
  B70: 'West Bromwich',
  B71: 'West Bromwich, Hill Top, Stone Cross',
  B72: 'Sutton Coldfield, Wylde Green, Maney',
  B73: 'Boldmere, New Oscott, Sutton Coldfield',
  B74: 'Four Oaks, Streetly, Sutton Coldfield',
  B75: 'Mere Green, Roughley, Sutton Coldfield',
  B76: 'Walmley, Minworth, Sutton Coldfield',
  B77: 'Tamworth, Wilnecote',
  B78: 'Fazeley, Kingsbury, Tamworth',
  B79: 'Tamworth',
  B80: 'Studley',
  B90: 'Shirley, Solihull',
  B91: 'Solihull',
  B92: 'Olton, Elmdon, Hampton-in-Arden',
  B93: 'Knowle, Dorridge, Bentley Heath',
  B94: 'Hockley Heath, Lapworth, Tanworth-in-Arden',
  B95: 'Henley-in-Arden',
  B96: 'Astwood Bank, Feckenham, Redditch',
  B97: 'Redditch, Webheath',
  B98: 'Redditch, Winyates',

  // ── BD · Bradford ──
  BD1: 'City centre',
  BD2: 'Eccleshill, Undercliffe',
  BD3: 'Barkerend, Bradford Moor, Thornbury',
  BD4: 'Bierley, Bowling, Tong',
  BD5: 'West Bowling, Little Horton',
  BD6: 'Buttershaw, Wibsey',
  BD7: 'Great Horton, Lidget Green',
  BD8: 'Manningham, Girlington',
  BD9: 'Heaton, Frizinghall',
  BD10: 'Idle, Thackley, Apperley Bridge',
  BD11: 'Birkenshaw, Drighlington',
  BD12: 'Wyke, Low Moor',
  BD13: 'Queensbury, Thornton, Denholme',
  BD14: 'Clayton',
  BD15: 'Allerton, Wilsden',
  BD16: 'Bingley, Cottingley',
  BD17: 'Baildon',
  BD18: 'Shipley, Saltaire',
  BD19: 'Cleckheaton',
  BD20: 'Silsden, Steeton, Sutton-in-Craven',
  BD21: 'Keighley',
  BD22: 'Haworth, Oxenhope, Oakworth',
  BD23: 'Skipton, Grassington',
  BD24: 'Settle',

  // ── BH · Bournemouth ──
  BH1: 'Town centre, East Cliff',
  BH2: 'West Cliff, Town centre',
  BH3: 'Talbot Woods, Meyrick Park',
  BH4: 'Westbourne',
  BH5: 'Boscombe, Pokesdown',
  BH6: 'Southbourne, Tuckton',
  BH7: 'Littledown, Iford, Boscombe East',
  BH8: 'Charminster, Queens Park',
  BH9: 'Winton, Moordown',
  BH10: 'Kinson, Ensbury Park, Northbourne',
  BH11: 'Bearwood, Wallisdown',
  BH12: 'Parkstone, Branksome, Alderney',
  BH13: 'Canford Cliffs, Sandbanks, Branksome Park',
  BH14: 'Lower Parkstone, Lilliput, Penn Hill',
  BH15: 'Poole, Hamworthy, Oakdale',
  BH16: 'Upton, Lytchett Matravers',
  BH17: 'Canford Heath, Creekmoor',
  BH18: 'Broadstone',
  BH19: 'Swanage',
  BH20: 'Wareham, Corfe Castle, Bovington',
  BH21: 'Wimborne, Colehill',
  BH22: 'Ferndown, West Moors',
  BH23: 'Christchurch, Highcliffe, Mudeford',
  BH24: 'Ringwood',
  BH25: 'New Milton, Barton on Sea',
  BH31: 'Verwood',

  // ── BN · Brighton & Hove ──
  BN1: 'City centre, North Laine, Preston Park, Patcham',
  BN2: 'Kemptown, Hanover, Woodingdean, Rottingdean',
  BN3: 'Hove',
  BN5: 'Henfield',
  BN6: 'Hassocks, Hurstpierpoint',
  BN7: 'Lewes',
  BN8: 'Ringmer, Newick',
  BN9: 'Newhaven',
  BN10: 'Peacehaven',
  BN11: 'Worthing',
  BN12: 'Goring-by-Sea, Ferring',
  BN13: 'Durrington, Worthing',
  BN14: 'Broadwater, Findon, Worthing',
  BN15: 'Lancing, Sompting',
  BN16: 'Rustington, East Preston, Angmering',
  BN17: 'Littlehampton',
  BN18: 'Arundel',
  BN20: 'Meads, Old Town, Eastbourne',
  BN21: 'Eastbourne',
  BN22: 'Hampden Park, Eastbourne',
  BN23: 'Langney, Sovereign Harbour, Eastbourne',
  BN24: 'Pevensey, Westham',
  BN25: 'Seaford',
  BN26: 'Polegate, Alfriston',
  BN27: 'Hailsham',
  BN41: 'Portslade',
  BN42: 'Southwick',
  BN43: 'Shoreham-by-Sea',
  BN44: 'Steyning',
  BN45: 'Poynings, Pyecombe',

  // ── BS · Bristol ──
  BS1: 'City centre, Redcliffe, Harbourside',
  BS2: 'St Pauls, St Philips, Kingsdown',
  BS3: 'Bedminster, Southville, Ashton',
  BS4: 'Brislington, Knowle, Totterdown',
  BS5: 'Easton, St George, Redfield',
  BS6: 'Redland, Cotham, Westbury Park',
  BS7: 'Bishopston, Horfield, Ashley Down',
  BS8: 'Clifton, Hotwells, Leigh Woods',
  BS9: 'Westbury-on-Trym, Henleaze, Stoke Bishop',
  BS10: 'Henbury, Brentry, Southmead',
  BS11: 'Avonmouth, Shirehampton, Lawrence Weston',
  BS13: 'Bishopsworth, Hartcliffe, Withywood',
  BS14: 'Whitchurch, Hengrove, Stockwood',
  BS15: 'Kingswood, Hanham, Cadbury Heath',
  BS16: 'Fishponds, Downend, Frenchay, Staple Hill, Emersons Green',
  BS20: 'Portishead, Pill',
  BS21: 'Clevedon',
  BS22: 'Worle, Weston-super-Mare',
  BS23: 'Weston-super-Mare',
  BS24: 'Hutton, Locking, Weston-super-Mare',
  BS25: 'Winscombe',
  BS26: 'Axbridge',
  BS27: 'Cheddar',
  BS28: 'Wedmore',
  BS29: 'Banwell',
  BS30: 'Warmley, Bitton, Oldland Common',
  BS31: 'Keynsham, Saltford',
  BS32: 'Bradley Stoke, Almondsbury',
  BS34: 'Filton, Patchway, Stoke Gifford',
  BS35: 'Thornbury, Alveston',
  BS36: 'Winterbourne, Frampton Cotterell',
  BS37: 'Yate, Chipping Sodbury',
  BS39: 'Clutton, Paulton, Temple Cloud',
  BS40: 'Chew Valley, Winford',
  BS41: 'Long Ashton',
  BS48: 'Nailsea, Backwell',
  BS49: 'Yatton, Congresbury',

  // ── CF · Cardiff ──
  CF3: 'Rumney, St Mellons',
  CF5: 'Canton, Fairwater, Ely, Llandaff',
  CF10: 'City centre, Cardiff Bay, Butetown',
  CF11: 'Grangetown, Riverside, Pontcanna',
  CF14: 'Whitchurch, Llanishen, Heath, Rhiwbina',
  CF15: 'Radyr, Taffs Well, Tongwynlais',
  CF23: 'Cyncoed, Pentwyn, Pontprennau',
  CF24: 'Roath, Cathays, Adamsdown, Splott',
  CF31: 'Bridgend',
  CF32: 'Sarn, Bryncethin, Ogmore Vale',
  CF33: 'Pyle, Kenfig Hill, North Cornelly',
  CF34: 'Maesteg',
  CF35: 'Pencoed, Coychurch',
  CF36: 'Porthcawl',
  CF37: 'Pontypridd, Treforest',
  CF38: 'Llantwit Fardre, Church Village',
  CF39: 'Porth, Tonyrefail',
  CF40: 'Tonypandy',
  CF41: 'Pentre',
  CF42: 'Treorchy',
  CF43: 'Ferndale',
  CF44: 'Aberdare',
  CF45: 'Mountain Ash',
  CF46: 'Treharris',
  CF47: 'Merthyr Tydfil',
  CF48: 'Troedyrhiw, Merthyr Tydfil',
  CF61: 'Llantwit Major',
  CF62: 'Barry, Rhoose',
  CF63: 'Barry',
  CF64: 'Penarth, Dinas Powys, Sully',
  CF71: 'Cowbridge',
  CF72: 'Llantrisant, Pontyclun, Talbot Green',
  CF81: 'Bargoed',
  CF82: 'Hengoed, Ystrad Mynach',
  CF83: 'Caerphilly',

  // ── CT · Canterbury ──
  CT1: 'City centre',
  CT2: 'St Dunstans, Harbledown, Sturry',
  CT3: 'Wingham, Littlebourne, Aylesham',
  CT4: 'Bridge, Chartham, Chilham',
  CT5: 'Whitstable',
  CT6: 'Herne Bay',
  CT7: 'Birchington',
  CT8: 'Westgate-on-Sea',
  CT9: 'Margate, Cliftonville',
  CT10: 'Broadstairs',
  CT11: 'Ramsgate',
  CT12: 'Minster, Manston, Cliffsend',
  CT13: 'Sandwich',
  CT14: 'Deal, Walmer',
  CT15: 'St Margarets, Eythorne, Dover',
  CT16: 'Dover, Whitfield',
  CT17: 'Dover, River',
  CT18: 'Hawkinge, Lyminge',
  CT19: 'Folkestone',
  CT20: 'Folkestone, Sandgate',
  CT21: 'Hythe',

  // ── DT · Dorchester ──
  DT1: 'Dorchester',
  DT2: 'Cerne Abbas, Puddletown, Maiden Newton',
  DT3: 'Chickerell, Preston, Weymouth',
  DT4: 'Weymouth, Wyke Regis',
  DT5: 'Portland',
  DT6: 'Bridport, West Bay, Burton Bradstock',
  DT7: 'Lyme Regis, Charmouth',
  DT8: 'Beaminster',
  DT9: 'Sherborne',
  DT10: 'Sturminster Newton',
  DT11: 'Blandford Forum',

  // ── EH · Edinburgh ──
  EH1: 'Old Town, Royal Mile',
  EH2: 'New Town, Princes Street',
  EH3: 'West End, Stockbridge, Tollcross, Fountainbridge',
  EH4: 'Dean Village, Comely Bank, Barnton, Cramond',
  EH5: 'Granton, Trinity',
  EH6: 'Leith, Newhaven',
  EH7: 'Leith Walk, Hillside, Lochend',
  EH8: 'Holyrood, Newington, Abbeyhill',
  EH9: 'Marchmont, Grange, Newington',
  EH10: 'Morningside, Bruntsfield, Fairmilehead',
  EH11: 'Gorgie, Dalry, Sighthill',
  EH12: 'Murrayfield, Corstorphine, Gyle',
  EH13: 'Colinton, Oxgangs',
  EH14: 'Slateford, Currie, Balerno, Juniper Green',
  EH15: 'Portobello, Joppa, Duddingston',
  EH16: 'Liberton, Craigmillar, Cameron Toll',
  EH17: 'Gilmerton, Moredun',
  EH18: 'Lasswade',
  EH19: 'Bonnyrigg',
  EH20: 'Loanhead',
  EH21: 'Musselburgh',
  EH22: 'Dalkeith',
  EH23: 'Gorebridge',
  EH24: 'Rosewell',
  EH25: 'Roslin',
  EH26: 'Penicuik',
  EH27: 'Kirknewton',
  EH28: 'Newbridge, Ratho',
  EH29: 'Kirkliston',
  EH30: 'South Queensferry',
  EH31: 'Gullane',
  EH32: 'Prestonpans, Longniddry',
  EH33: 'Tranent',
  EH34: 'Pencaitland',
  EH35: 'Ormiston',
  EH36: 'Humbie',
  EH37: 'Pathhead',
  EH38: 'Heriot',
  EH39: 'North Berwick',
  EH40: 'East Linton',
  EH41: 'Haddington',
  EH42: 'Dunbar',
  EH43: 'Walkerburn',
  EH44: 'Innerleithen',
  EH45: 'Peebles',
  EH46: 'West Linton',
  EH47: 'Whitburn, Fauldhouse',
  EH48: 'Bathgate, Armadale',
  EH49: 'Linlithgow',
  EH51: 'Boness',
  EH52: 'Broxburn, Uphall',
  EH53: 'Mid Calder, Pumpherston, Livingston',
  EH54: 'Livingston',
  EH55: 'West Calder',

  // ── G · Glasgow ──
  G1: 'City centre, Merchant City',
  G2: 'City centre, Blythswood',
  G3: 'Finnieston, Park, Anderston, Kelvingrove',
  G4: 'Cowcaddens, Woodlands, Townhead',
  G5: 'Gorbals, Laurieston',
  G11: 'Partick, Hyndland, Broomhill',
  G12: 'West End, Hillhead, Kelvinside, Dowanhill',
  G13: 'Anniesland, Knightswood, Jordanhill',
  G14: 'Whiteinch, Scotstoun',
  G15: 'Drumchapel',
  G20: 'Maryhill, North Kelvinside, Ruchill',
  G21: 'Springburn, Balornock, Barmulloch',
  G22: 'Milton, Possilpark',
  G23: 'Lambhill, Summerston',
  G31: 'Dennistoun, Parkhead, Haghill',
  G32: 'Shettleston, Tollcross, Carmyle',
  G33: 'Riddrie, Stepps, Cranhill, Ruchazie',
  G34: 'Easterhouse',
  G40: 'Bridgeton, Calton, Dalmarnock',
  G41: 'Pollokshields, Shawlands, Strathbungo',
  G42: 'Govanhill, Queens Park, Mount Florida, Battlefield',
  G43: 'Newlands, Mansewood',
  G44: 'Cathcart, Croftfoot, Kings Park',
  G45: 'Castlemilk',
  G46: 'Giffnock, Thornliebank',
  G51: 'Govan, Ibrox',
  G52: 'Cardonald, Hillington, Penilee',
  G53: 'Pollok, Darnley, Nitshill',
  G60: 'Bowling, Old Kilpatrick',
  G61: 'Bearsden',
  G62: 'Milngavie',
  G63: 'Balfron, Killearn, Drymen',
  G64: 'Bishopbriggs, Torrance',
  G65: 'Kilsyth',
  G66: 'Kirkintilloch, Lenzie',
  G67: 'Cumbernauld',
  G68: 'Cumbernauld, Dullatur',
  G69: 'Baillieston, Moodiesburn, Chryston',
  G71: 'Uddingston, Bothwell, Viewpark',
  G72: 'Cambuslang, Blantyre',
  G73: 'Rutherglen',
  G74: 'East Kilbride',
  G75: 'East Kilbride',
  G76: 'Clarkston, Busby, Eaglesham',
  G77: 'Newton Mearns',
  G78: 'Barrhead, Neilston',
  G81: 'Clydebank',
  G82: 'Dumbarton',
  G83: 'Alexandria, Balloch',
  G84: 'Helensburgh',

  // ── GL · Gloucester ──
  GL1: 'City centre',
  GL2: 'Quedgeley, Longlevens, Hardwicke',
  GL3: 'Churchdown, Brockworth, Hucclecote',
  GL4: 'Abbeydale, Matson, Tuffley',
  GL5: 'Stroud',
  GL6: 'Nailsworth, Painswick, Chalford',
  GL7: 'Cirencester, Fairford, Lechlade',
  GL8: 'Tetbury',
  GL9: 'Badminton',
  GL10: 'Stonehouse',
  GL11: 'Dursley, Cam',
  GL12: 'Wotton-under-Edge, Charfield',
  GL13: 'Berkeley',
  GL14: 'Cinderford, Newnham',
  GL15: 'Lydney',
  GL16: 'Coleford',
  GL17: 'Drybrook, Mitcheldean',
  GL18: 'Newent',
  GL19: 'Staunton, Tirley',
  GL20: 'Tewkesbury',
  GL50: 'Cheltenham',
  GL51: 'Hesters Way, Benhall, Cheltenham',
  GL52: 'Prestbury, Bishops Cleeve, Cheltenham',
  GL53: 'Leckhampton, Charlton Kings, Cheltenham',
  GL54: 'Bourton-on-the-Water, Stow-on-the-Wold, Winchcombe',
  GL55: 'Chipping Campden',
  GL56: 'Moreton-in-Marsh',

  // ── HG · Harrogate ──
  HG1: 'Harrogate',
  HG2: 'Pannal, Harrogate',
  HG3: 'Killinghall, Pateley Bridge, Harrogate',
  HG4: 'Ripon',
  HG5: 'Knaresborough',

  // ── HU · Hull ──
  HU1: 'City centre, Old Town',
  HU2: 'City centre',
  HU3: 'Anlaby Road, West Hull',
  HU4: 'Anlaby Common, Gipsyville',
  HU5: 'Newland, The Avenues',
  HU6: 'Orchard Park, University',
  HU7: 'Bransholme, Kingswood, Sutton',
  HU8: 'Sutton-on-Hull, Garden Village',
  HU9: 'East Hull, Marfleet',
  HU10: 'Anlaby, Kirk Ella, Willerby',
  HU11: 'Bilton, Sproatley, Aldbrough',
  HU12: 'Hedon, Patrington',
  HU13: 'Hessle',
  HU14: 'North Ferriby',
  HU15: 'Brough, Elloughton, South Cave',
  HU16: 'Cottingham',
  HU17: 'Beverley',
  HU18: 'Hornsea',
  HU19: 'Withernsea',
  HU20: 'Walkington',

  // ── L · Liverpool ──
  L1: 'City centre, Ropewalks, Chinatown',
  L2: 'City centre, Commercial District',
  L3: 'Waterfront, Vauxhall, City centre',
  L4: 'Anfield, Walton, Kirkdale',
  L5: 'Everton, Kirkdale, Vauxhall',
  L6: 'Kensington, Fairfield, Everton',
  L7: 'Edge Hill, Kensington, Fairfield',
  L8: 'Toxteth, Dingle, Baltic Triangle',
  L9: 'Aintree, Walton, Orrell Park',
  L10: 'Aintree, Fazakerley',
  L11: 'Croxteth, Norris Green, Clubmoor',
  L12: 'West Derby, Croxteth Park',
  L13: 'Old Swan, Stoneycroft, Tuebrook',
  L14: 'Knotty Ash, Dovecot, Page Moss',
  L15: 'Wavertree',
  L16: 'Childwall, Broadgreen, Bowring Park',
  L17: 'Aigburth, Sefton Park, St Michaels',
  L18: 'Mossley Hill, Allerton, Calderstones',
  L19: 'Garston, Grassendale, Cressington',
  L20: 'Bootle, Orrell',
  L21: 'Litherland, Seaforth, Ford',
  L22: 'Waterloo, Brighton-le-Sands',
  L23: 'Crosby, Blundellsands, Thornton',
  L24: 'Speke, Hale',
  L25: 'Woolton, Gateacre, Hunts Cross',
  L26: 'Halewood',
  L27: 'Netherley',
  L28: 'Stockbridge Village',
  L29: 'Lunt, Sefton',
  L30: 'Netherton, Bootle',
  L31: 'Maghull, Lydiate, Melling',
  L32: 'Kirkby, Northwood, Westvale',
  L33: 'Kirkby, Tower Hill',
  L34: 'Prescot, Knowsley Village',
  L35: 'Whiston, Rainhill',
  L36: 'Huyton, Roby',
  L37: 'Formby',
  L38: 'Hightown',
  L39: 'Ormskirk, Aughton',
  L40: 'Burscough, Rufford',

  // ── LE · Leicester ──
  LE1: 'City centre',
  LE2: 'Clarendon Park, Knighton, Stoneygate, Aylestone, Oadby',
  LE3: 'Braunstone, Westcotes, Glenfield',
  LE4: 'Belgrave, Beaumont Leys, Birstall, Thurmaston',
  LE5: 'Evington, Humberstone, Thurnby',
  LE6: 'Groby, Ratby',
  LE7: 'Anstey, Syston, Scraptoft, Queniborough',
  LE8: 'Blaby, Countesthorpe, Kibworth',
  LE9: 'Broughton Astley, Earl Shilton, Narborough',
  LE10: 'Hinckley, Burbage',
  LE11: 'Loughborough',
  LE12: 'Shepshed, Quorn, Barrow upon Soar',
  LE13: 'Melton Mowbray',
  LE14: 'Asfordby, Melton Mowbray',
  LE15: 'Oakham, Uppingham',
  LE16: 'Market Harborough',
  LE17: 'Lutterworth',
  LE18: 'Wigston',
  LE19: 'Enderby, Narborough',
  LE65: 'Ashby-de-la-Zouch',
  LE67: 'Coalville, Ibstock',

  // ── LS · Leeds ──
  LS1: 'City centre',
  LS2: 'City centre, University, Woodhouse',
  LS3: 'Little Woodhouse, Burley Road',
  LS4: 'Burley, Kirkstall',
  LS5: 'Kirkstall, Hawksworth',
  LS6: 'Headingley, Hyde Park, Meanwood',
  LS7: 'Chapel Allerton, Chapeltown, Meanwood',
  LS8: 'Roundhay, Oakwood, Harehills',
  LS9: 'Harehills, Cross Green, Richmond Hill',
  LS10: 'Hunslet, Middleton, Belle Isle',
  LS11: 'Beeston, Holbeck',
  LS12: 'Armley, Wortley, Farnley',
  LS13: 'Bramley, Rodley, Swinnow',
  LS14: 'Seacroft, Whinmoor, Killingbeck',
  LS15: 'Crossgates, Halton, Temple Newsam',
  LS16: 'Adel, Cookridge, Holt Park, Bramhope',
  LS17: 'Alwoodley, Moortown, Shadwell',
  LS18: 'Horsforth',
  LS19: 'Yeadon, Rawdon',
  LS20: 'Guiseley',
  LS21: 'Otley',
  LS22: 'Wetherby',
  LS23: 'Boston Spa, Bramham, Thorp Arch',
  LS24: 'Tadcaster',
  LS25: 'Garforth, Kippax, Sherburn in Elmet',
  LS26: 'Rothwell, Oulton, Woodlesford',
  LS27: 'Morley, Gildersome',
  LS28: 'Pudsey, Farsley, Stanningley',
  LS29: 'Ilkley, Burley in Wharfedale, Menston',

  // ── M · Manchester ──
  M1: 'City centre, Piccadilly, Northern Quarter',
  M2: 'City centre, Deansgate, St Peters Square',
  M3: 'Deansgate, Castlefield, Chapel Street',
  M4: 'Ancoats, Northern Quarter, New Islington',
  M5: 'Ordsall, Seedley, Weaste',
  M6: 'Pendleton, Irlams o th Height, Langworthy',
  M7: 'Higher Broughton, Kersal, Lower Broughton',
  M8: 'Cheetham Hill, Crumpsall',
  M9: 'Blackley, Harpurhey',
  M11: 'Clayton, Openshaw, Beswick',
  M12: 'Ardwick, Longsight',
  M13: 'Chorlton-on-Medlock, Ardwick, Longsight',
  M14: 'Fallowfield, Rusholme, Moss Side',
  M15: 'Hulme, Castlefield, University',
  M16: 'Old Trafford, Whalley Range, Firswood',
  M17: 'Trafford Park',
  M18: 'Gorton, Abbey Hey',
  M19: 'Levenshulme, Burnage',
  M20: 'Didsbury, Withington',
  M21: 'Chorlton-cum-Hardy',
  M22: 'Wythenshawe, Northenden, Sharston',
  M23: 'Baguley, Roundthorn, Wythenshawe',
  M24: 'Middleton',
  M25: 'Prestwich',
  M26: 'Radcliffe',
  M27: 'Swinton, Pendlebury, Clifton',
  M28: 'Worsley, Walkden',
  M29: 'Tyldesley, Astley',
  M30: 'Eccles, Monton',
  M31: 'Carrington, Partington',
  M32: 'Stretford',
  M33: 'Sale',
  M34: 'Denton, Audenshaw',
  M35: 'Failsworth',
  M38: 'Little Hulton',
  M40: 'Newton Heath, Moston, Miles Platting',
  M41: 'Urmston, Flixton, Davyhulme',
  M43: 'Droylsden',
  M44: 'Irlam, Cadishead',
  M45: 'Whitefield',
  M46: 'Atherton',
  M50: 'Salford Quays, MediaCityUK',
  M90: 'Manchester Airport',

  // ── NE · Newcastle upon Tyne ──
  NE1: 'City centre, Quayside',
  NE2: 'Jesmond, Sandyford, Spital Tongues',
  NE3: 'Gosforth, Kingston Park, Fawdon',
  NE4: 'Fenham, Arthurs Hill, Benwell',
  NE5: 'Westerhope, Blakelaw, Newbiggin Hall',
  NE6: 'Heaton, Byker, Walker',
  NE7: 'High Heaton, Benton',
  NE8: 'Gateshead',
  NE9: 'Low Fell, Wrekenton',
  NE10: 'Felling, Leam Lane, Wardley',
  NE11: 'Dunston, Team Valley, Lobley Hill',
  NE12: 'Killingworth, Longbenton, Forest Hall',
  NE13: 'Dinnington, Hazlerigg, Wideopen',
  NE15: 'Lemington, Newburn, Throckley',
  NE16: 'Whickham, Sunniside, Burnopfield',
  NE17: 'Chopwell',
  NE18: 'Stamfordham',
  NE19: 'Otterburn',
  NE20: 'Ponteland, Darras Hall',
  NE21: 'Blaydon',
  NE22: 'Bedlington',
  NE23: 'Cramlington',
  NE24: 'Blyth',
  NE25: 'Monkseaton, Seaton Delaval, Whitley Bay',
  NE26: 'Whitley Bay',
  NE27: 'Shiremoor, Backworth',
  NE28: 'Wallsend, Howdon',
  NE29: 'North Shields, Preston',
  NE30: 'Tynemouth, Cullercoats, North Shields',
  NE31: 'Hebburn',
  NE32: 'Jarrow',
  NE33: 'South Shields',
  NE34: 'Harton, Cleadon, South Shields',
  NE35: 'Boldon Colliery',
  NE36: 'East Boldon, West Boldon',
  NE37: 'Washington',
  NE38: 'Washington',
  NE39: 'Rowlands Gill',
  NE40: 'Ryton, Crawcrook',
  NE41: 'Wylam',
  NE42: 'Prudhoe',
  NE43: 'Stocksfield',
  NE44: 'Riding Mill',
  NE45: 'Corbridge',
  NE46: 'Hexham',
  NE47: 'Allendale, Haydon Bridge',
  NE48: 'Bellingham',
  NE49: 'Haltwhistle',
  NE61: 'Morpeth',
  NE62: 'Stakeford, Guide Post, Ashington',
  NE63: 'Ashington',
  NE64: 'Newbiggin-by-the-Sea',
  NE65: 'Rothbury, Amble, Warkworth',
  NE66: 'Alnwick, Beadnell, Embleton',
  NE67: 'Chathill',
  NE68: 'Seahouses',
  NE69: 'Bamburgh',
  NE70: 'Belford',
  NE71: 'Wooler',

  // ── NG · Nottingham ──
  NG1: 'City centre, Lace Market, Hockley',
  NG2: 'West Bridgford, The Meadows, Sneinton',
  NG3: 'Mapperley, St Anns, Carrington',
  NG4: 'Carlton, Gedling, Netherfield',
  NG5: 'Sherwood, Arnold, Bestwood',
  NG6: 'Bulwell, Basford, Bestwood Village',
  NG7: 'Lenton, Radford, Hyson Green, The Park',
  NG8: 'Wollaton, Aspley, Bilborough',
  NG9: 'Beeston, Chilwell, Stapleford',
  NG10: 'Long Eaton, Sandiacre',
  NG11: 'Clifton, Ruddington, Wilford',
  NG12: 'Radcliffe on Trent, Cotgrave, Keyworth',
  NG13: 'Bingham, Whatton',
  NG14: 'Burton Joyce, Lowdham, Calverton',
  NG15: 'Hucknall, Ravenshead',
  NG16: 'Eastwood, Kimberley, Nuthall',
  NG17: 'Sutton-in-Ashfield, Kirkby-in-Ashfield',
  NG18: 'Mansfield',
  NG19: 'Mansfield Woodhouse, Forest Town',
  NG20: 'Warsop, Shirebrook',
  NG21: 'Rainworth, Edwinstowe, Blidworth',
  NG22: 'Ollerton, New Ollerton',
  NG23: 'Collingham, Newark',
  NG24: 'Newark-on-Trent',
  NG25: 'Southwell',
  NG31: 'Grantham',
  NG32: 'Grantham',
  NG33: 'Colsterworth, Corby Glen',
  NG34: 'Sleaford',

  // ── OX · Oxford ──
  OX1: 'City centre, Grandpont',
  OX2: 'Jericho, Summertown, North Oxford',
  OX3: 'Headington, Marston',
  OX4: 'Cowley, Iffley, East Oxford',
  OX5: 'Kidlington',
  OX7: 'Chipping Norton, Charlbury',
  OX9: 'Thame',
  OX10: 'Wallingford',
  OX11: 'Didcot',
  OX12: 'Wantage, Grove',
  OX13: 'Kingston Bagpuize, Abingdon',
  OX14: 'Abingdon',
  OX15: 'Bloxham, Banbury',
  OX16: 'Banbury',
  OX17: 'Kings Sutton, Banbury',
  OX18: 'Carterton, Bampton, Burford',
  OX20: 'Woodstock',
  OX25: 'Upper Heyford, Bicester',
  OX26: 'Bicester',
  OX27: 'Bicester',
  OX28: 'Witney',
  OX29: 'Eynsham, Witney',
  OX33: 'Wheatley, Horspath',
  OX39: 'Chinnor',
  OX44: 'Chalgrove, Garsington',
  OX49: 'Watlington',

  // ── S · Sheffield ──
  S1: 'City centre',
  S2: 'Heeley, Norfolk Park, Manor, Arbourthorne',
  S3: 'Kelham Island, Neepsend, Netherthorpe',
  S4: 'Pitsmoor, Grimesthorpe, Burngreave',
  S5: 'Firth Park, Shiregreen, Parson Cross',
  S6: 'Hillsborough, Walkley, Stannington, Loxley',
  S7: 'Nether Edge, Abbeydale, Millhouses',
  S8: 'Woodseats, Meadowhead, Norton, Greenhill',
  S9: 'Attercliffe, Darnall, Tinsley, Meadowhall',
  S10: 'Broomhill, Crookes, Fulwood, Ranmoor',
  S11: 'Ecclesall, Sharrow, Greystones, Endcliffe',
  S12: 'Gleadless, Intake, Hackenthorpe, Frecheville',
  S13: 'Handsworth, Woodhouse, Richmond',
  S14: 'Gleadless Valley',
  S17: 'Dore, Totley, Bradway',
  S18: 'Dronfield',
  S20: 'Mosborough, Halfway, Beighton, Sothall',
  S21: 'Eckington, Killamarsh',
  S25: 'Dinnington, Laughton, Anston',
  S26: 'Aston, Swallownest, Kiveton Park',
  S35: 'Chapeltown, Ecclesfield, High Green',
  S36: 'Penistone, Stocksbridge',
  S40: 'Chesterfield',
  S41: 'Whittington, Newbold, Chesterfield',
  S42: 'Wingerworth, Holymoorside, Chesterfield',
  S43: 'Staveley, Barlborough, Brimington',
  S44: 'Bolsover, Clowne',
  S45: 'Clay Cross',
  S60: 'Rotherham, Whiston, Canklow',
  S61: 'Greasbrough, Kimberworth, Rotherham',
  S62: 'Rawmarsh, Parkgate',
  S63: 'Wath-upon-Dearne, Bolton upon Dearne, Goldthorpe',
  S64: 'Mexborough, Swinton',
  S65: 'Thrybergh, Dalton, Rotherham',
  S66: 'Maltby, Wickersley, Bramley',
  S70: 'Barnsley, Worsbrough',
  S71: 'Royston, Monk Bretton, Barnsley',
  S72: 'Cudworth, Grimethorpe, Shafton',
  S73: 'Wombwell, Darfield',
  S74: 'Hoyland, Elsecar',
  S75: 'Dodworth, Darton, Mapplewell, Barnsley',
  S80: 'Worksop',
  S81: 'Carlton in Lindrick, Langold, Worksop',

  // ── SA · Swansea ──
  SA1: 'City centre, Marina, Mount Pleasant',
  SA2: 'Sketty, Uplands, Killay',
  SA3: 'Mumbles, Gower, Bishopston',
  SA4: 'Gorseinon, Pontarddulais, Penllergaer',
  SA5: 'Fforestfach, Cwmbwrla, Portmead',
  SA6: 'Morriston, Clydach',
  SA7: 'Birchgrove, Llansamlet',
  SA8: 'Pontardawe',
  SA9: 'Ystradgynlais',
  SA10: 'Skewen, Bryncoch, Neath',
  SA11: 'Neath',
  SA12: 'Aberavon, Baglan, Port Talbot',
  SA13: 'Margam, Cwmavon, Port Talbot',
  SA14: 'Llangennech, Llanelli',
  SA15: 'Llanelli',
  SA16: 'Burry Port, Pembrey',
  SA17: 'Kidwelly, Ferryside',
  SA18: 'Ammanford',
  SA19: 'Llandeilo, Llangadog',
  SA20: 'Llandovery',
  SA31: 'Carmarthen',
  SA32: 'Nantgaredig, Carmarthen',
  SA33: 'Laugharne, St Clears, Carmarthen',
  SA34: 'Whitland',
  SA35: 'Llanfyrnach',
  SA36: 'Glogue',
  SA37: 'Boncath',
  SA38: 'Newcastle Emlyn',
  SA39: 'Pencader',
  SA40: 'Llanybydder',
  SA41: 'Crymych',
  SA42: 'Newport (Pembrokeshire)',
  SA43: 'Cardigan',
  SA44: 'Llandysul',
  SA45: 'New Quay',
  SA46: 'Aberaeron',
  SA47: 'Llanarth',
  SA48: 'Lampeter',
  SA61: 'Haverfordwest',
  SA62: 'St Davids, Broad Haven',
  SA63: 'Clarbeston Road',
  SA64: 'Goodwick',
  SA65: 'Fishguard',
  SA66: 'Clynderwen',
  SA67: 'Narberth',
  SA68: 'Kilgetty',
  SA69: 'Saundersfoot',
  SA70: 'Tenby',
  SA71: 'Pembroke',
  SA72: 'Pembroke Dock',
  SA73: 'Milford Haven',

  // ── YO · York ──
  YO1: 'City centre',
  YO7: 'Thirsk',
  YO8: 'Selby',
  YO10: 'Fulford, Heslington, University',
  YO11: 'Scarborough, South Cliff',
  YO12: 'Scalby, Newby, Scarborough',
  YO13: 'Cloughton, Scarborough',
  YO14: 'Filey',
  YO15: 'Bridlington',
  YO16: 'Bridlington',
  YO17: 'Malton, Norton',
  YO18: 'Pickering',
  YO19: 'Dunnington, Wheldrake, Escrick',
  YO21: 'Sleights, Whitby',
  YO22: 'Whitby, Robin Hoods Bay',
  YO23: 'Bishopthorpe, Copmanthorpe, South Bank',
  YO24: 'Acomb, Dringhouses, Holgate',
  YO25: 'Driffield',
  YO26: 'Poppleton, Acomb',
  YO30: 'Clifton, Rawcliffe, Skelton',
  YO31: 'Heworth, Huntington, Layerthorpe',
  YO32: 'Haxby, Wigginton, Strensall',
  YO41: 'Stamford Bridge, Pocklington',
  YO42: 'Pocklington',
  YO43: 'Market Weighton',
  YO51: 'Boroughbridge',
  YO60: 'Castle Howard, Sheriff Hutton',
  YO61: 'Easingwold',
  YO62: 'Helmsley, Kirkbymoorside',
};

const CACHE = new Map<string, string[]>();

/** Localities for a postcode district, lead first; empty when the district is not listed. */
export function districtLocalities(district: string): string[] {
  const key = district.trim().toUpperCase();
  let v = CACHE.get(key);
  if (!v) {
    v = (RAW[key] ?? '').split(',').map((s) => s.trim()).filter(Boolean);
    CACHE.set(key, v);
  }
  return v;
}

/** Districts listed, for tests and coverage checks. */
export function listedDistricts(): string[] {
  return Object.keys(RAW);
}
