/** Localities per postcode district: AL, CB, CM, CO. Lead locality first. */
export const EAST_OF_ENGLAND_A: Record<string, string> = {
  // ── AL · St Albans ──
  AL1: 'St Albans, City centre, Fleetville, Sopwell',
  AL2: 'St Albans, London Colney, Bricket Wood, Chiswell Green',
  AL3: 'St Albans, Redbourn, Markyate',
  AL4: 'St Albans, Marshalswick, Sandridge, Wheathampstead',
  AL5: 'Harpenden',
  AL6: 'Welwyn',
  AL7: 'Welwyn Garden City, Panshanger',
  AL8: 'Welwyn Garden City, Town centre',
  AL9: 'Hatfield, Brookmans Park, Welham Green',
  AL10: 'Hatfield',
  // ── CB · Cambridge ──
  CB1: 'Cambridge, Mill Road, Cherry Hinton, Petersfield',
  CB2: 'Cambridge, City centre, Newnham, Trumpington',
  CB3: 'Cambridge, Newnham, Girton, Madingley',
  CB4: 'Cambridge, Chesterton, Arbury, Kings Hedges',
  CB5: 'Cambridge, Abbey, Fen Ditton',
  CB6: 'Ely, Littleport, Soham',
  CB7: 'Ely, Soham, Fordham',
  CB8: 'Newmarket',
  CB9: 'Haverhill',
  CB10: 'Saffron Walden',
  CB11: 'Saffron Walden',
  CB21: 'Linton, Fulbourn, Great Shelford',
  CB22: 'Sawston, Great Shelford, Stapleford',
  CB23: 'Cambourne, Comberton, Bar Hill',
  CB24: 'Histon, Cottenham, Waterbeach',
  CB25: 'Burwell, Bottisham',
  // ── CM · Chelmsford ──
  CM0: 'Burnham-on-Crouch, Southminster',
  CM1: 'Chelmsford, City centre, Broomfield, Writtle',
  CM2: 'Chelmsford, Great Baddow, Galleywood, Springfield',
  CM3: 'Chelmsford, South Woodham Ferrers, Danbury',
  CM4: 'Ingatestone',
  CM5: 'Ongar',
  CM6: 'Great Dunmow',
  CM7: 'Braintree',
  CM8: 'Witham',
  CM9: 'Maldon, Heybridge',
  CM11: 'Billericay',
  CM12: 'Billericay',
  CM13: 'Brentwood, Hutton, Warley',
  CM14: 'Brentwood, Town centre',
  CM15: 'Brentwood, Shenfield, Pilgrims Hatch',
  CM16: 'Epping, Theydon Bois',
  CM17: 'Harlow, Old Harlow',
  CM18: 'Harlow',
  CM19: 'Harlow',
  CM20: 'Harlow, Town centre',
  CM21: 'Sawbridgeworth',
  CM22: 'Bishops Stortford, Stansted Mountfitchet',
  CM23: 'Bishops Stortford',
  CM24: 'Stansted Mountfitchet',
  CM77: 'Braintree, Great Notley',
  // ── CO · Colchester ──
  CO1: 'Colchester, City centre, Hythe',
  CO2: 'Colchester, Shrub End, Old Heath, Berechurch',
  CO3: 'Colchester, Lexden, Prettygate, Stanway',
  CO4: 'Colchester, Highwoods, Greenstead, Mile End',
  CO5: 'Tiptree, West Mersea, Kelvedon',
  CO6: 'Coggeshall, Earls Colne, West Bergholt',
  CO7: 'Brightlingsea, Wivenhoe, Dedham',
  CO8: 'Bures',
  CO9: 'Halstead',
  CO10: 'Sudbury, Long Melford',
  CO11: 'Manningtree, Mistley',
  CO12: 'Harwich, Dovercourt',
  CO13: 'Frinton-on-Sea',
  CO14: 'Walton-on-the-Naze',
  CO15: 'Clacton-on-Sea',
  CO16: 'Clacton-on-Sea, St Osyth',
};
