/** Localities per postcode district: DE, LN, NN. Lead locality first. (LE and NG are in the core table.) */
export const EAST_MIDLANDS: Record<string, string> = {
  // ── DE · Derby ──
  DE1: 'Derby, City centre, Cathedral Quarter',
  DE3: 'Mickleover',
  DE4: 'Matlock, Wirksworth, Cromford',
  DE5: 'Ripley',
  DE6: 'Ashbourne',
  DE7: 'Ilkeston, West Hallam',
  DE11: 'Swadlincote',
  DE12: 'Measham, Overseal',
  DE13: 'Burton upon Trent, Barton-under-Needwood',
  DE14: 'Burton upon Trent, Town centre',
  DE15: 'Burton upon Trent, Stapenhill, Winshill',
  DE21: 'Derby, Chaddesden, Spondon, Oakwood',
  DE22: 'Derby, Allestree, Darley Abbey, Mackworth',
  DE23: 'Derby, Littleover, Normanton, Sunny Hill',
  DE24: 'Derby, Alvaston, Allenton, Sinfin',
  DE45: 'Bakewell',
  DE55: 'Alfreton, South Normanton',
  DE56: 'Belper, Duffield',
  DE65: 'Hilton, Etwall, Willington',
  DE72: 'Borrowash, Draycott, Ockbrook',
  DE73: 'Chellaston, Melbourne',
  DE74: 'Castle Donington, Kegworth',
  DE75: 'Heanor',
  // ── LN · Lincoln ──
  LN1: 'Lincoln, City centre, West End, Uphill',
  LN2: 'Lincoln, Ermine, Nettleham',
  LN3: 'Cherry Willingham, Welton',
  LN4: 'Bracebridge Heath, Branston, Woodhall Spa',
  LN5: 'Lincoln, Boultham, Waddington',
  LN6: 'Lincoln, North Hykeham, Birchwood',
  LN7: 'Market Rasen, Caistor',
  LN8: 'Market Rasen',
  LN9: 'Horncastle',
  LN10: 'Woodhall Spa',
  LN11: 'Louth',
  LN12: 'Mablethorpe',
  LN13: 'Alford',
  // ── NN · Northampton ──
  NN1: 'Northampton, Town centre, Kingsley',
  NN2: 'Northampton, Kingsthorpe, Whitehills',
  NN3: 'Northampton, Weston Favell, Moulton, Boothville',
  NN4: 'Northampton, Wootton, Hunsbury, Far Cotton',
  NN5: 'Northampton, Duston, St James, Dallington',
  NN6: 'Northampton, Brixworth, Long Buckby',
  NN7: 'Northampton, Roade, Bugbrooke',
  NN8: 'Wellingborough',
  NN9: 'Wellingborough, Finedon, Irthlingborough',
  NN10: 'Rushden, Higham Ferrers',
  NN11: 'Daventry',
  NN12: 'Towcester',
  NN13: 'Brackley',
  NN14: 'Kettering, Thrapston, Desborough',
  NN15: 'Kettering, Barton Seagrave, Burton Latimer',
  NN16: 'Kettering, Town centre',
  NN17: 'Corby, Town centre',
  NN18: 'Corby, Oakley Vale',
  NN29: 'Wellingborough, Wollaston',
};
