/** Localities per postcode district: IP, LU, NR, PE, SG, SS, WD. Lead locality first. */
export const EAST_OF_ENGLAND_B: Record<string, string> = {
  // ── IP · Ipswich ──
  IP1: 'Ipswich, Town centre, Westgate, Whitton',
  IP2: 'Ipswich, Stoke, Chantry, Maidenhall',
  IP3: 'Ipswich, Gainsborough, Priory Heath, Ravenswood',
  IP4: 'Ipswich, California, Rushmere, Broke Hall',
  IP5: 'Kesgrave, Martlesham Heath',
  IP6: 'Needham Market, Claydon',
  IP7: 'Hadleigh',
  IP8: 'Ipswich, Sproughton, Bramford',
  IP9: 'Ipswich, Holbrook, Capel St Mary',
  IP10: 'Ipswich, Nacton, Bucklesham',
  IP11: 'Felixstowe',
  IP12: 'Woodbridge',
  IP13: 'Woodbridge, Wickham Market, Framlingham',
  IP14: 'Stowmarket',
  IP15: 'Aldeburgh',
  IP16: 'Leiston',
  IP17: 'Saxmundham',
  IP18: 'Southwold',
  IP19: 'Halesworth',
  IP20: 'Harleston',
  IP21: 'Eye',
  IP22: 'Diss',
  IP23: 'Eye',
  IP24: 'Thetford',
  IP25: 'Thetford, Watton',
  IP26: 'Thetford, Mundford',
  IP27: 'Brandon, Lakenheath',
  IP28: 'Bury St Edmunds, Mildenhall',
  IP29: 'Bury St Edmunds, Horringer',
  IP30: 'Bury St Edmunds, Woolpit',
  IP31: 'Bury St Edmunds, Ixworth',
  IP32: 'Bury St Edmunds, Moreton Hall',
  IP33: 'Bury St Edmunds, Town centre',
  // ── LU · Luton ──
  LU1: 'Luton, Town centre, Farley Hill, Caddington',
  LU2: 'Luton, Stopsley, Round Green, Wigmore',
  LU3: 'Luton, Leagrave, Limbury, Sundon Park',
  LU4: 'Luton, Lewsey, Challney, Leagrave',
  LU5: 'Dunstable, Houghton Regis',
  LU6: 'Dunstable, Kensworth',
  LU7: 'Leighton Buzzard, Linslade',
  // ── NR · Norwich ──
  NR1: 'Norwich, City centre, Thorpe Hamlet, Lakenham',
  NR2: 'Norwich, Golden Triangle, Eaton, Earlham',
  NR3: 'Norwich, Mile Cross, Catton, Sprowston',
  NR4: 'Norwich, Eaton, Cringleford, University',
  NR5: 'Norwich, Bowthorpe, Costessey, Earlham',
  NR6: 'Norwich, Hellesdon, Old Catton, Sprowston',
  NR7: 'Norwich, Thorpe St Andrew, Sprowston, Dussindale',
  NR8: 'Taverham, Drayton',
  NR9: 'Hethersett, Wymondham, Barford',
  NR10: 'Horsford, Aylsham, Reepham',
  NR11: 'Aylsham, Cromer',
  NR12: 'North Walsham, Stalham, Wroxham',
  NR13: 'Brundall, Acle, Blofield',
  NR14: 'Poringland, Loddon, Framingham Earl',
  NR15: 'Long Stratton, Tasburgh',
  NR16: 'Attleborough',
  NR17: 'Attleborough',
  NR18: 'Wymondham',
  NR19: 'Dereham',
  NR20: 'Dereham, North Elmham',
  NR21: 'Fakenham',
  NR22: 'Walsingham',
  NR23: 'Wells-next-the-Sea',
  NR24: 'Melton Constable',
  NR25: 'Holt',
  NR26: 'Sheringham',
  NR27: 'Cromer',
  NR28: 'North Walsham',
  NR29: 'Great Yarmouth, Martham, Hemsby',
  NR30: 'Great Yarmouth, Town centre, Caister-on-Sea',
  NR31: 'Great Yarmouth, Gorleston, Bradwell',
  NR32: 'Lowestoft, Town centre, Oulton Broad',
  NR33: 'Lowestoft, Pakefield, Carlton Colville',
  NR34: 'Beccles',
  NR35: 'Bungay',
  // ── PE · Peterborough ──
  PE1: 'Peterborough, City centre, Dogsthorpe, Eastfield',
  PE2: 'Peterborough, Hampton, Orton, Woodston',
  PE3: 'Peterborough, Bretton, Longthorpe, Westwood',
  PE4: 'Peterborough, Werrington, Walton, Paston',
  PE5: 'Peterborough, Ailsworth, Castor',
  PE6: 'Market Deeping, Crowland, Glinton',
  PE7: 'Whittlesey, Yaxley, Hampton',
  PE8: 'Oundle',
  PE9: 'Stamford',
  PE10: 'Bourne',
  PE11: 'Spalding',
  PE12: 'Holbeach, Long Sutton',
  PE13: 'Wisbech',
  PE14: 'Wisbech, Outwell',
  PE15: 'March',
  PE16: 'Chatteris',
  PE19: 'St Neots',
  PE20: 'Boston, Kirton',
  PE21: 'Boston',
  PE22: 'Boston, Old Leake',
  PE23: 'Spilsby',
  PE24: 'Skegness, Wainfleet',
  PE25: 'Skegness',
  PE26: 'Ramsey, Huntingdon',
  PE27: 'St Ives',
  PE28: 'Huntingdon, Kimbolton',
  PE29: 'Huntingdon',
  PE30: 'Kings Lynn, Gaywood, South Wootton',
  PE31: 'Kings Lynn, Hunstanton, Burnham Market',
  PE32: 'Kings Lynn, Swaffham',
  PE33: 'Kings Lynn, Downham Market',
  PE34: 'Kings Lynn, Terrington St Clement',
  PE35: 'Sandringham',
  PE36: 'Hunstanton',
  PE37: 'Swaffham',
  PE38: 'Downham Market',
  // ── SG · Stevenage ──
  SG1: 'Stevenage, Town centre, Old Town, Chells',
  SG2: 'Stevenage, Shephall, Broadwater, Poplars',
  SG3: 'Knebworth',
  SG4: 'Hitchin, Whitwell, Kimpton',
  SG5: 'Hitchin, Town centre, Ickleford',
  SG6: 'Letchworth Garden City',
  SG7: 'Baldock',
  SG8: 'Royston, Melbourn',
  SG9: 'Buntingford',
  SG10: 'Much Hadham',
  SG11: 'Ware, Standon',
  SG12: 'Ware',
  SG13: 'Hertford, Bengeo',
  SG14: 'Hertford, Sele Farm',
  SG15: 'Arlesey',
  SG16: 'Henlow',
  SG17: 'Shefford',
  SG18: 'Biggleswade',
  SG19: 'Sandy, Potton',
  // ── SS · Southend-on-Sea ──
  SS0: 'Westcliff-on-Sea, Chalkwell',
  SS1: 'Southend-on-Sea, Town centre, Thorpe Bay',
  SS2: 'Southend-on-Sea, Prittlewell, Southchurch',
  SS3: 'Shoeburyness, Great Wakering',
  SS4: 'Rochford, Ashingdon',
  SS5: 'Hockley, Hullbridge',
  SS6: 'Rayleigh',
  SS7: 'Benfleet, Thundersley, Hadleigh',
  SS8: 'Canvey Island',
  SS9: 'Leigh-on-Sea, Eastwood',
  SS11: 'Wickford',
  SS12: 'Wickford',
  SS13: 'Basildon, Pitsea',
  SS14: 'Basildon, Town centre',
  SS15: 'Basildon, Laindon',
  SS16: 'Basildon, Langdon Hills, Vange',
  SS17: 'Stanford-le-Hope, Corringham',
  // ── WD · Watford ──
  WD3: 'Rickmansworth, Chorleywood, Croxley Green',
  WD4: 'Kings Langley',
  WD5: 'Abbots Langley',
  WD6: 'Borehamwood, Elstree',
  WD7: 'Radlett, Shenley',
  WD17: 'Watford, Town centre, Cassiobury',
  WD18: 'Watford, West Watford, Holywell',
  WD19: 'Watford, Oxhey, South Oxhey, Carpenders Park',
  WD23: 'Bushey',
  WD24: 'Watford, North Watford, Leavesden',
  WD25: 'Watford, Garston, Leavesden',
};
