/** Localities per postcode district: E, EC, N, NW. Lead locality first. */
export const LONDON_A: Record<string, string> = {
  // ── E · East London ──
  E1: 'Whitechapel, Shoreditch, Spitalfields, Stepney',
  E2: 'Bethnal Green, Shoreditch, Haggerston',
  E3: 'Bow, Bromley-by-Bow, Mile End',
  E4: 'Chingford, Highams Park',
  E5: 'Clapton, Lower Clapton',
  E6: 'East Ham, Beckton',
  E7: 'Forest Gate, Upton Park',
  E8: 'Hackney, Dalston, London Fields',
  E9: 'Homerton, Hackney Wick, Victoria Park',
  E10: 'Leyton',
  E11: 'Leytonstone, Wanstead, Snaresbrook',
  E12: 'Manor Park, Little Ilford',
  E13: 'Plaistow, West Ham',
  E14: 'Canary Wharf, Poplar, Isle of Dogs, Limehouse',
  E15: 'Stratford, West Ham, Maryland',
  E16: 'Canning Town, Silvertown, Royal Docks, Custom House',
  E17: 'Walthamstow',
  E18: 'South Woodford',
  E20: 'Olympic Park, Stratford',
  // ── EC · City of London ──
  EC1: 'Clerkenwell, Farringdon, Barbican, Finsbury',
  EC2: 'Moorgate, Liverpool Street, Shoreditch',
  EC3: 'Aldgate, Tower Hill, Monument, Fenchurch Street',
  EC4: 'St Pauls, Fleet Street, Blackfriars, Temple',
  // ── N · North London ──
  N1: 'Islington, Angel, Barnsbury, Kings Cross, Canonbury',
  N2: 'East Finchley, Fortis Green',
  N3: 'Finchley, Church End',
  N4: 'Finsbury Park, Manor House, Harringay',
  N5: 'Highbury',
  N6: 'Highgate',
  N7: 'Holloway, Tufnell Park',
  N8: 'Hornsey, Crouch End, Harringay',
  N9: 'Lower Edmonton',
  N10: 'Muswell Hill',
  N11: 'New Southgate, Friern Barnet, Bounds Green',
  N12: 'North Finchley, Woodside Park',
  N13: 'Palmers Green',
  N14: 'Southgate, Oakwood',
  N15: 'Seven Sisters, South Tottenham',
  N16: 'Stoke Newington, Stamford Hill',
  N17: 'Tottenham',
  N18: 'Upper Edmonton',
  N19: 'Archway, Upper Holloway, Tufnell Park',
  N20: 'Whetstone, Totteridge',
  N21: 'Winchmore Hill, Grange Park',
  N22: 'Wood Green, Alexandra Palace',
  // ── NW · North West London ──
  NW1: 'Camden Town, Regents Park, Euston, Primrose Hill, Kings Cross',
  NW2: 'Cricklewood, Willesden Green, Dollis Hill',
  NW3: 'Hampstead, Belsize Park, Swiss Cottage',
  NW4: 'Hendon, Brent Cross',
  NW5: 'Kentish Town, Gospel Oak, Dartmouth Park',
  NW6: 'Kilburn, West Hampstead, Queens Park',
  NW7: 'Mill Hill',
  NW8: 'St Johns Wood, Primrose Hill',
  NW9: 'Colindale, Kingsbury, The Hyde',
  NW10: 'Willesden, Harlesden, Kensal Green, Park Royal',
  NW11: 'Golders Green, Hampstead Garden Suburb',
};
