/** Localities per postcode district: BR, CR, EN, HA, IG, KT, RM, SM, TW, UB. Lead locality first. */
export const LONDON_C: Record<string, string> = {
  // ── BR · Bromley ──
  BR1: 'Bromley, Town centre, Bickley, Sundridge Park',
  BR2: 'Bromley, Hayes, Bickley, Shortlands',
  BR3: 'Beckenham, Eden Park, Elmers End',
  BR4: 'West Wickham',
  BR5: 'Orpington, St Mary Cray, Petts Wood',
  BR6: 'Orpington, Farnborough, Chelsfield',
  BR7: 'Chislehurst',
  BR8: 'Swanley',
  // ── CR · Croydon ──
  CR0: 'Croydon, Town centre, Addiscombe, Shirley, New Addington',
  CR2: 'South Croydon, Sanderstead, Selsdon',
  CR3: 'Caterham, Whyteleafe',
  CR4: 'Mitcham',
  CR5: 'Coulsdon',
  CR6: 'Warlingham',
  CR7: 'Thornton Heath',
  CR8: 'Purley, Kenley',
  // ── EN · Enfield ──
  EN1: 'Enfield, Town centre, Bush Hill Park',
  EN2: 'Enfield, Enfield Chase, Botany Bay',
  EN3: 'Enfield, Ponders End, Enfield Lock, Enfield Highway',
  EN4: 'Cockfosters, Hadley Wood, New Barnet',
  EN5: 'Barnet, High Barnet, Arkley',
  EN6: 'Potters Bar, South Mimms',
  EN7: 'Cheshunt, Goffs Oak',
  EN8: 'Cheshunt, Waltham Cross',
  EN9: 'Waltham Abbey',
  EN10: 'Broxbourne',
  EN11: 'Hoddesdon',
  // ── HA · Harrow ──
  HA0: 'Wembley, Sudbury, Alperton',
  HA1: 'Harrow, Town centre, Harrow on the Hill',
  HA2: 'Harrow, South Harrow, North Harrow, Rayners Lane',
  HA3: 'Harrow Weald, Wealdstone, Kenton',
  HA4: 'Ruislip, Eastcote',
  HA5: 'Pinner, Hatch End, Eastcote',
  HA6: 'Northwood',
  HA7: 'Stanmore',
  HA8: 'Edgware, Burnt Oak',
  HA9: 'Wembley, Wembley Park, Tokyngton',
  // ── IG · Ilford ──
  IG1: 'Ilford, Town centre, Cranbrook',
  IG2: 'Gants Hill, Newbury Park, Aldborough Hatch',
  IG3: 'Seven Kings, Goodmayes',
  IG4: 'Redbridge',
  IG5: 'Clayhall',
  IG6: 'Barkingside, Hainault',
  IG7: 'Chigwell',
  IG8: 'Woodford Green, Woodford Bridge',
  IG9: 'Buckhurst Hill',
  IG10: 'Loughton',
  IG11: 'Barking',
  // ── KT · Kingston upon Thames ──
  KT1: 'Kingston upon Thames, Town centre, Norbiton',
  KT2: 'Kingston upon Thames, Kingston Hill, Coombe',
  KT3: 'New Malden',
  KT4: 'Worcester Park',
  KT5: 'Surbiton, Berrylands, Tolworth',
  KT6: 'Surbiton, Tolworth, Long Ditton',
  KT7: 'Thames Ditton',
  KT8: 'East Molesey, West Molesey, Hampton Court',
  KT9: 'Chessington',
  KT10: 'Esher, Claygate, Hinchley Wood',
  KT11: 'Cobham, Oxshott',
  KT12: 'Walton-on-Thames, Hersham',
  KT13: 'Weybridge',
  KT14: 'West Byfleet, Byfleet',
  KT15: 'Addlestone, New Haw',
  KT16: 'Chertsey, Ottershaw',
  KT17: 'Epsom, Ewell, Stoneleigh',
  KT18: 'Epsom, Epsom Downs, Tattenham Corner',
  KT19: 'Epsom, West Ewell, Stoneleigh',
  KT20: 'Tadworth, Kingswood, Burgh Heath',
  KT21: 'Ashtead',
  KT22: 'Leatherhead, Fetcham, Oxshott',
  KT23: 'Great Bookham, Little Bookham',
  KT24: 'East Horsley, West Horsley, Effingham',
  // ── RM · Romford ──
  RM1: 'Romford, Town centre, Rise Park',
  RM2: 'Gidea Park',
  RM3: 'Harold Wood, Harold Hill',
  RM4: 'Havering-atte-Bower, Noak Hill, Stapleford Abbotts',
  RM5: 'Collier Row',
  RM6: 'Chadwell Heath, Marks Gate',
  RM7: 'Romford, Rush Green, Mawneys',
  RM8: 'Dagenham, Becontree',
  RM9: 'Dagenham',
  RM10: 'Dagenham, Dagenham East',
  RM11: 'Hornchurch, Emerson Park, Ardleigh Green',
  RM12: 'Hornchurch, Elm Park',
  RM13: 'Rainham, South Hornchurch',
  RM14: 'Upminster, Cranham',
  RM15: 'South Ockendon, Aveley',
  RM16: 'Grays, Chafford Hundred, Chadwell St Mary',
  RM17: 'Grays',
  RM18: 'Tilbury',
  RM19: 'Purfleet',
  RM20: 'Grays, West Thurrock, Lakeside',
  // ── SM · Sutton ──
  SM1: 'Sutton, Town centre, Rosehill',
  SM2: 'Sutton, Belmont, South Sutton',
  SM3: 'Cheam, North Cheam',
  SM4: 'Morden',
  SM5: 'Carshalton',
  SM6: 'Wallington, Beddington',
  SM7: 'Banstead',
  // ── TW · Twickenham ──
  TW1: 'Twickenham, St Margarets',
  TW2: 'Twickenham, Whitton, Strawberry Hill',
  TW3: 'Hounslow, Town centre',
  TW4: 'Hounslow West, Hounslow Heath',
  TW5: 'Heston, Cranford',
  TW6: 'Heathrow Airport',
  TW7: 'Isleworth, Osterley',
  TW8: 'Brentford',
  TW9: 'Richmond, Kew, North Sheen',
  TW10: 'Richmond, Ham, Petersham, Richmond Hill',
  TW11: 'Teddington',
  TW12: 'Hampton, Hampton Hill',
  TW13: 'Feltham, Hanworth',
  TW14: 'Feltham, Bedfont, Hatton',
  TW15: 'Ashford',
  TW16: 'Sunbury-on-Thames',
  TW17: 'Shepperton',
  TW18: 'Staines-upon-Thames',
  TW19: 'Stanwell, Wraysbury',
  TW20: 'Egham, Englefield Green',
  // ── UB · Uxbridge ──
  UB1: 'Southall',
  UB2: 'Southall, Norwood Green',
  UB3: 'Hayes, Harlington',
  UB4: 'Hayes, Yeading',
  UB5: 'Northolt',
  UB6: 'Greenford, Perivale',
  UB7: 'West Drayton, Yiewsley, Harmondsworth',
  UB8: 'Uxbridge, Cowley, Hillingdon',
  UB9: 'Denham, Harefield',
  UB10: 'Hillingdon, Ickenham',
  UB11: 'Stockley Park',
};
