/** Localities per postcode district: SE, SW, W, WC. Lead locality first. */
export const LONDON_B: Record<string, string> = {
  // ── SE · South East London ──
  SE1: 'Southwark, Waterloo, Bermondsey, Borough, London Bridge',
  SE2: 'Abbey Wood',
  SE3: 'Blackheath, Kidbrooke, Westcombe Park',
  SE4: 'Brockley, Crofton Park, Honor Oak',
  SE5: 'Camberwell, Denmark Hill',
  SE6: 'Catford, Bellingham, Hither Green',
  SE7: 'Charlton',
  SE8: 'Deptford',
  SE9: 'Eltham, Mottingham, New Eltham',
  SE10: 'Greenwich, Maze Hill',
  SE11: 'Kennington, Vauxhall, Lambeth',
  SE12: 'Lee, Grove Park, Hither Green',
  SE13: 'Lewisham, Hither Green, Ladywell',
  SE14: 'New Cross, New Cross Gate',
  SE15: 'Peckham, Nunhead',
  SE16: 'Rotherhithe, Surrey Quays, Bermondsey',
  SE17: 'Walworth, Elephant and Castle',
  SE18: 'Woolwich, Plumstead',
  SE19: 'Crystal Palace, Upper Norwood',
  SE20: 'Penge, Anerley',
  SE21: 'Dulwich, West Dulwich',
  SE22: 'East Dulwich',
  SE23: 'Forest Hill, Honor Oak',
  SE24: 'Herne Hill, Tulse Hill',
  SE25: 'South Norwood',
  SE26: 'Sydenham',
  SE27: 'West Norwood, Tulse Hill',
  SE28: 'Thamesmead',
  // ── SW · South West London ──
  SW1: 'Westminster, Belgravia, Pimlico, Victoria, St Jamess',
  SW2: 'Brixton, Streatham Hill, Tulse Hill',
  SW3: 'Chelsea, Brompton, Knightsbridge',
  SW4: 'Clapham',
  SW5: 'Earls Court',
  SW6: 'Fulham, Parsons Green',
  SW7: 'South Kensington, Knightsbridge',
  SW8: 'South Lambeth, Nine Elms, Vauxhall, Battersea',
  SW9: 'Stockwell, Brixton',
  SW10: 'West Brompton, Chelsea Harbour',
  SW11: 'Battersea, Clapham Junction',
  SW12: 'Balham',
  SW13: 'Barnes',
  SW14: 'Mortlake, East Sheen',
  SW15: 'Putney, Roehampton',
  SW16: 'Streatham, Norbury',
  SW17: 'Tooting',
  SW18: 'Wandsworth, Earlsfield, Southfields',
  SW19: 'Wimbledon, Colliers Wood, South Wimbledon',
  SW20: 'Raynes Park, West Wimbledon',
  // ── W · West London ──
  W1: 'Mayfair, Soho, Marylebone, Fitzrovia, Oxford Street',
  W2: 'Paddington, Bayswater, Hyde Park',
  W3: 'Acton',
  W4: 'Chiswick',
  W5: 'Ealing',
  W6: 'Hammersmith',
  W7: 'Hanwell',
  W8: 'Kensington, Holland Park',
  W9: 'Maida Vale, Little Venice, Warwick Avenue',
  W10: 'North Kensington, Ladbroke Grove, Kensal Town',
  W11: 'Notting Hill, Holland Park, Ladbroke Grove',
  W12: 'Shepherds Bush, White City',
  W13: 'West Ealing',
  W14: 'West Kensington, Olympia',
  // ── WC · Central London ──
  WC1: 'Bloomsbury, Holborn, Kings Cross, Russell Square',
  WC2: 'Covent Garden, Strand, Holborn, Leicester Square',
};
