/** Localities per postcode district: BB, BL, CA, CH, CW, FY. Lead locality first. */
export const NORTH_WEST_A: Record<string, string> = {
  // ── BB · Blackburn ──
  BB1: 'Blackburn, Town centre, Whitebirk',
  BB2: 'Blackburn, Mill Hill, Feniscowles',
  BB3: 'Darwen',
  BB4: 'Rawtenstall, Haslingden, Rossendale',
  BB5: 'Accrington, Oswaldtwistle, Clayton-le-Moors',
  BB6: 'Great Harwood',
  BB7: 'Clitheroe, Whalley',
  BB8: 'Colne',
  BB9: 'Nelson, Barrowford',
  BB10: 'Burnley, Brunshaw, Pike Hill',
  BB11: 'Burnley, Town centre, Rose Hill',
  BB12: 'Burnley, Padiham, Hapton',
  BB18: 'Barnoldswick, Earby',
  // ── BL · Bolton ──
  BL0: 'Ramsbottom, Edenfield',
  BL1: 'Bolton, Town centre, Smithills, Heaton',
  BL2: 'Bolton, Breightmet, Harwood, Tonge Moor',
  BL3: 'Bolton, Great Lever, Daubhill',
  BL4: 'Farnworth, Kearsley',
  BL5: 'Westhoughton',
  BL6: 'Horwich, Blackrod, Lostock',
  BL7: 'Bromley Cross, Egerton, Edgworth',
  BL8: 'Bury, Tottington, Greenmount',
  BL9: 'Bury, Town centre, Walmersley',
  // ── CA · Carlisle ──
  CA1: 'Carlisle, City centre, Botcherby, Harraby',
  CA2: 'Carlisle, Denton Holme, Currock, Morton',
  CA3: 'Carlisle, Stanwix, Belah, Kingstown',
  CA4: 'Wetheral, Dalston',
  CA5: 'Dalston, Burgh by Sands',
  CA6: 'Brampton, Longtown',
  CA7: 'Wigton, Silloth, Aspatria',
  CA8: 'Brampton, Gilsland',
  CA9: 'Alston',
  CA10: 'Penrith, Shap, Appleby',
  CA11: 'Penrith',
  CA12: 'Keswick',
  CA13: 'Cockermouth',
  CA14: 'Workington',
  CA15: 'Maryport',
  CA16: 'Appleby-in-Westmorland',
  CA17: 'Kirkby Stephen',
  CA18: 'Ravenglass',
  CA19: 'Holmrook',
  CA20: 'Seascale',
  CA21: 'Beckermet',
  CA22: 'Egremont',
  CA23: 'Cleator',
  CA24: 'Cleator Moor',
  CA25: 'Cleator Moor',
  CA26: 'Frizington',
  CA27: 'St Bees',
  CA28: 'Whitehaven',
  // ── CH · Chester ──
  CH1: 'Chester, City centre, Blacon, Saughall',
  CH2: 'Chester, Hoole, Upton, Newton',
  CH3: 'Chester, Boughton, Christleton, Tarvin',
  CH4: 'Chester, Handbridge, Curzon Park, Saltney',
  CH5: 'Deeside, Connahs Quay, Hawarden',
  CH6: 'Flint, Bagillt',
  CH7: 'Mold, Buckley',
  CH8: 'Holywell',
  CH41: 'Birkenhead, Town centre',
  CH42: 'Rock Ferry, Tranmere, Prenton',
  CH43: 'Oxton, Prenton, Bidston',
  CH44: 'Wallasey, Seacombe, Poulton',
  CH45: 'New Brighton, Wallasey Village',
  CH46: 'Moreton, Leasowe',
  CH47: 'Hoylake, Meols',
  CH48: 'West Kirby, Caldy',
  CH49: 'Upton, Greasby, Woodchurch',
  CH60: 'Heswall',
  CH61: 'Pensby, Thingwall, Irby',
  CH62: 'Bromborough, Port Sunlight, Eastham',
  CH63: 'Bebington, Spital, Thornton Hough',
  CH64: 'Neston, Parkgate, Willaston',
  CH65: 'Ellesmere Port, Town centre',
  CH66: 'Ellesmere Port, Great Sutton, Little Sutton',
  // ── CW · Crewe ──
  CW1: 'Crewe, Town centre, Leighton, Haslington',
  CW2: 'Crewe, Wistaston, Shavington',
  CW3: 'Audlem, Wybunbury, Betley',
  CW4: 'Holmes Chapel, Goostrey',
  CW5: 'Nantwich',
  CW6: 'Tarporley, Kelsall',
  CW7: 'Winsford',
  CW8: 'Northwich, Hartford, Weaverham',
  CW9: 'Northwich, Town centre, Lostock Gralam',
  CW10: 'Middlewich',
  CW11: 'Sandbach',
  CW12: 'Congleton',
  // ── FY · Blackpool ──
  FY1: 'Blackpool, Town centre, Promenade',
  FY2: 'Blackpool, Bispham, Norbreck',
  FY3: 'Blackpool, Layton, Marton, Staining',
  FY4: 'Blackpool, South Shore, Marton',
  FY5: 'Cleveleys, Thornton',
  FY6: 'Poulton-le-Fylde, Knott End',
  FY7: 'Fleetwood',
  FY8: 'Lytham St Annes',
};
