/** Localities per postcode district: LA, OL, PR, SK, WA, WN. Lead locality first. (L and M are in the core table.) */
export const NORTH_WEST_B: Record<string, string> = {
  // ── LA · Lancaster ──
  LA1: 'Lancaster, City centre, Bowerham, Scotforth',
  LA2: 'Lancaster, Galgate, Caton, Halton',
  LA3: 'Morecambe, Heysham, Overton',
  LA4: 'Morecambe, Bare, Torrisholme',
  LA5: 'Carnforth',
  LA6: 'Kirkby Lonsdale, Ingleton',
  LA7: 'Milnthorpe',
  LA8: 'Kendal, Staveley, Burneside',
  LA9: 'Kendal',
  LA10: 'Sedbergh',
  LA11: 'Grange-over-Sands, Cartmel',
  LA12: 'Ulverston',
  LA13: 'Barrow-in-Furness',
  LA14: 'Barrow-in-Furness, Walney',
  LA15: 'Dalton-in-Furness',
  LA16: 'Askam-in-Furness',
  LA17: 'Kirkby-in-Furness',
  LA18: 'Millom',
  LA19: 'Millom',
  LA20: 'Broughton-in-Furness',
  LA21: 'Coniston',
  LA22: 'Ambleside, Grasmere',
  LA23: 'Windermere, Bowness-on-Windermere',
  // ── OL · Oldham ──
  OL1: 'Oldham, Town centre, Derker',
  OL2: 'Royton, Shaw',
  OL3: 'Uppermill, Delph, Saddleworth',
  OL4: 'Oldham, Lees, Springhead, Grotton',
  OL5: 'Mossley',
  OL6: 'Ashton-under-Lyne',
  OL7: 'Ashton-under-Lyne',
  OL8: 'Oldham, Hollinwood, Werneth',
  OL9: 'Chadderton',
  OL10: 'Heywood',
  OL11: 'Rochdale, Castleton, Norden',
  OL12: 'Rochdale, Whitworth, Wardle',
  OL13: 'Bacup',
  OL14: 'Todmorden',
  OL15: 'Littleborough',
  OL16: 'Rochdale, Town centre, Milnrow',
  // ── PR · Preston ──
  PR1: 'Preston, City centre, Fishwick, Avenham',
  PR2: 'Preston, Fulwood, Ashton-on-Ribble, Ribbleton',
  PR3: 'Garstang, Longridge, Goosnargh',
  PR4: 'Kirkham, Wrea Green, Longton',
  PR5: 'Bamber Bridge, Walton-le-Dale, Lostock Hall',
  PR6: 'Chorley, Adlington, Whittle-le-Woods',
  PR7: 'Chorley, Euxton, Eccleston',
  PR8: 'Southport, Birkdale, Ainsdale',
  PR9: 'Southport, Churchtown, Marshside',
  PR25: 'Leyland',
  PR26: 'Leyland, Farington',
  // ── SK · Stockport ──
  SK1: 'Stockport, Town centre, Portwood',
  SK2: 'Stockport, Offerton, Great Moor',
  SK3: 'Stockport, Edgeley, Davenport, Adswood',
  SK4: 'Heaton Moor, Heaton Mersey, Heaton Chapel',
  SK5: 'Reddish, Brinnington',
  SK6: 'Marple, Romiley, Bredbury',
  SK7: 'Bramhall, Hazel Grove',
  SK8: 'Cheadle, Cheadle Hulme, Gatley',
  SK9: 'Wilmslow, Alderley Edge, Handforth',
  SK10: 'Macclesfield, Bollington, Prestbury',
  SK11: 'Macclesfield, Town centre, Sutton',
  SK12: 'Poynton, Disley',
  SK13: 'Glossop, Hadfield',
  SK14: 'Hyde, Hattersley, Broadbottom',
  SK15: 'Stalybridge',
  SK16: 'Dukinfield',
  SK17: 'Buxton',
  SK22: 'New Mills',
  SK23: 'Whaley Bridge, Chapel-en-le-Frith',
  // ── WA · Warrington ──
  WA1: 'Warrington, Town centre, Padgate, Woolston',
  WA2: 'Warrington, Orford, Winwick, Fearnhead',
  WA3: 'Birchwood, Culcheth, Lowton, Golborne',
  WA4: 'Warrington, Stockton Heath, Grappenhall, Latchford',
  WA5: 'Warrington, Great Sankey, Penketh, Burtonwood',
  WA6: 'Frodsham, Helsby',
  WA7: 'Runcorn',
  WA8: 'Widnes',
  WA9: 'St Helens, Sutton, Clock Face',
  WA10: 'St Helens, Town centre, Eccleston',
  WA11: 'St Helens, Haydock, Rainford',
  WA12: 'Newton-le-Willows',
  WA13: 'Lymm',
  WA14: 'Altrincham, Bowdon, Broadheath',
  WA15: 'Hale, Timperley, Hale Barns',
  WA16: 'Knutsford',
  // ── WN · Wigan ──
  WN1: 'Wigan, Town centre, Swinley',
  WN2: 'Hindley, Aspull, Ince',
  WN3: 'Wigan, Worsley Mesnes, Goose Green',
  WN4: 'Ashton-in-Makerfield',
  WN5: 'Orrell, Billinge, Pemberton',
  WN6: 'Standish, Shevington, Appley Bridge',
  WN7: 'Leigh',
  WN8: 'Skelmersdale, Upholland, Parbold',
};
