/** Localities per postcode district: DH, DL, SR, TS. Lead locality first. (NE is in the core table.) */
export const NORTH_EAST: Record<string, string> = {
  // ── DH · Durham ──
  DH1: 'Durham, Gilesgate, Framwellgate Moor, Belmont',
  DH2: 'Chester-le-Street, Pelton, Ouston',
  DH3: 'Chester-le-Street, Birtley',
  DH4: 'Houghton-le-Spring, Fence Houses',
  DH5: 'Houghton-le-Spring, Hetton-le-Hole',
  DH6: 'Coxhoe, Bowburn, Thornley',
  DH7: 'Brandon, Langley Park, Esh Winning',
  DH8: 'Consett, Leadgate, Shotley Bridge',
  DH9: 'Stanley, Annfield Plain, Tanfield',
  // ── DL · Darlington ──
  DL1: 'Darlington, Haughton, Eastbourne',
  DL2: 'Darlington, Middleton St George, Hurworth',
  DL3: 'Darlington, Cockerton, West End',
  DL4: 'Shildon',
  DL5: 'Newton Aycliffe',
  DL6: 'Northallerton',
  DL7: 'Northallerton',
  DL8: 'Leyburn, Hawes, Bedale',
  DL9: 'Catterick Garrison',
  DL10: 'Richmond',
  DL11: 'Richmond, Reeth',
  DL12: 'Barnard Castle',
  DL13: 'Bishop Auckland, Crook, Wolsingham',
  DL14: 'Bishop Auckland',
  DL15: 'Crook, Willington',
  DL16: 'Spennymoor',
  DL17: 'Ferryhill',
  // ── SR · Sunderland ──
  SR1: 'City centre',
  SR2: 'Ashbrooke, Hendon, Ryhope',
  SR3: 'Silksworth, Doxford Park, Farringdon',
  SR4: 'Pallion, Millfield, Pennywell',
  SR5: 'Southwick, Castletown, Hylton',
  SR6: 'Roker, Seaburn, Fulwell, Whitburn',
  SR7: 'Seaham, Murton',
  SR8: 'Peterlee, Horden, Easington',
  // ── TS · Middlesbrough ──
  TS1: 'Middlesbrough, Town centre',
  TS2: 'Middlesbrough, Port Clarence',
  TS3: 'Middlesbrough, Berwick Hills, Park End',
  TS4: 'Middlesbrough, Grove Hill, Marton',
  TS5: 'Middlesbrough, Linthorpe, Acklam',
  TS6: 'Eston, Grangetown, Normanby',
  TS7: 'Marton, Nunthorpe, Ormesby',
  TS8: 'Coulby Newham, Hemlington, Stainton',
  TS9: 'Stokesley, Great Ayton',
  TS10: 'Redcar',
  TS11: 'Redcar, Marske-by-the-Sea',
  TS12: 'Saltburn-by-the-Sea, Skelton, Brotton',
  TS13: 'Loftus, Staithes',
  TS14: 'Guisborough',
  TS15: 'Yarm',
  TS16: 'Eaglescliffe',
  TS17: 'Thornaby-on-Tees, Ingleby Barwick',
  TS18: 'Stockton-on-Tees, Town centre',
  TS19: 'Stockton-on-Tees, Fairfield, Hardwick',
  TS20: 'Stockton-on-Tees, Norton',
  TS21: 'Sedgefield, Stillington',
  TS22: 'Billingham, Wynyard',
  TS23: 'Billingham',
  TS24: 'Hartlepool, Headland',
  TS25: 'Hartlepool, Seaton Carew',
  TS26: 'Hartlepool, Park',
  TS27: 'Hartlepool, Blackhall, Hesleden',
  TS28: 'Wingate',
  TS29: 'Trimdon',
};
