/** Localities per postcode district: BT (all of Northern Ireland). Lead locality first. */
export const NORTHERN_IRELAND: Record<string, string> = {
  BT1: 'City centre, Cathedral Quarter',
  BT2: 'City centre, Linen Quarter',
  BT3: 'Titanic Quarter, Harbour Estate',
  BT4: 'Ballyhackamore, Belmont, Stormont',
  BT5: 'Castlereagh, Cregagh, Knock',
  BT6: 'Ravenhill, Woodstock, Castlereagh',
  BT7: 'Ormeau, Botanic, Queens Quarter',
  BT8: 'Newtownbreda, Carryduff, Four Winds',
  BT9: 'Malone, Stranmillis, Lisburn Road',
  BT10: 'Finaghy',
  BT11: 'Andersonstown, Lenadoon',
  BT12: 'Falls, Sandy Row, Village',
  BT13: 'Shankill, Woodvale',
  BT14: 'Crumlin Road, Ballysillan',
  BT15: 'York Road, Antrim Road, Sailortown',
  BT16: 'Dundonald',
  BT17: 'Dunmurry, Twinbrook, Lagmore',
  BT18: 'Holywood',
  BT19: 'Bangor, Groomsport',
  BT20: 'Bangor',
  BT21: 'Donaghadee',
  BT22: 'Newtownards, Portaferry, Ards Peninsula',
  BT23: 'Newtownards, Comber',
  BT24: 'Ballynahinch',
  BT25: 'Dromore',
  BT26: 'Hillsborough',
  BT27: 'Lisburn',
  BT28: 'Lisburn',
  BT29: 'Crumlin, Aldergrove',
  BT30: 'Downpatrick',
  BT31: 'Castlewellan',
  BT32: 'Banbridge',
  BT33: 'Newcastle',
  BT34: 'Newry, Warrenpoint, Kilkeel',
  BT35: 'Newry, Bessbrook, Crossmaglen',
  BT36: 'Newtownabbey, Glengormley',
  BT37: 'Newtownabbey, Whiteabbey',
  BT38: 'Carrickfergus',
  BT39: 'Ballyclare',
  BT40: 'Larne',
  BT41: 'Antrim, Randalstown',
  BT42: 'Ballymena',
  BT43: 'Ballymena',
  BT44: 'Ballymena, Cushendall',
  BT45: 'Magherafelt',
  BT46: 'Maghera',
  BT47: 'Londonderry, Waterside, Eglinton',
  BT48: 'Londonderry, Cityside',
  BT49: 'Limavady',
  BT51: 'Coleraine, Garvagh',
  BT52: 'Coleraine',
  BT53: 'Ballymoney',
  BT54: 'Ballycastle',
  BT55: 'Portstewart',
  BT56: 'Portrush',
  BT57: 'Bushmills',
  BT60: 'Armagh, Markethill',
  BT61: 'Armagh',
  BT62: 'Craigavon, Portadown',
  BT63: 'Craigavon, Portadown',
  BT64: 'Craigavon',
  BT65: 'Craigavon',
  BT66: 'Craigavon, Lurgan',
  BT67: 'Craigavon, Lurgan, Moira',
  BT68: 'Caledon',
  BT69: 'Aughnacloy',
  BT70: 'Dungannon',
  BT71: 'Dungannon, Coalisland',
  BT74: 'Enniskillen',
  BT75: 'Fivemiletown',
  BT76: 'Clogher',
  BT77: 'Augher',
  BT78: 'Omagh',
  BT79: 'Omagh',
  BT80: 'Cookstown',
  BT81: 'Castlederg',
  BT82: 'Strabane',
  BT92: 'Enniskillen, Lisnaskea',
  BT93: 'Enniskillen, Belleek',
  BT94: 'Enniskillen, Irvinestown',
};
