/** Localities per postcode district: DG, FK, KA, KY, ML, PA, TD. Lead locality first. */
export const SCOTLAND_SOUTH: Record<string, string> = {
  // ── DG · Dumfries ──
  DG1: 'Dumfries, Georgetown, Heathhall',
  DG2: 'Dumfries, Maxwelltown, Lochside',
  DG3: 'Thornhill',
  DG4: 'Sanquhar',
  DG5: 'Dalbeattie',
  DG6: 'Kirkcudbright',
  DG7: 'Castle Douglas',
  DG8: 'Newton Stewart',
  DG9: 'Stranraer',
  DG10: 'Moffat',
  DG11: 'Lockerbie',
  DG12: 'Annan',
  DG13: 'Langholm',
  DG14: 'Canonbie',
  DG16: 'Gretna',
  // ── FK · Falkirk ──
  FK1: 'Falkirk, Camelon, Bainsford',
  FK2: 'Grangemouth, Polmont, Larbert',
  FK3: 'Grangemouth',
  FK4: 'Bonnybridge',
  FK5: 'Larbert, Stenhousemuir',
  FK6: 'Denny',
  FK7: 'Stirling, Bannockburn, St Ninians',
  FK8: 'Stirling, Raploch, Cambusbarron',
  FK9: 'Bridge of Allan, University of Stirling',
  FK10: 'Alloa, Clackmannan',
  FK11: 'Menstrie',
  FK12: 'Alva',
  FK13: 'Tillicoultry',
  FK14: 'Dollar',
  FK15: 'Dunblane',
  FK16: 'Doune',
  FK17: 'Callander',
  FK18: 'Lochearnhead',
  FK19: 'Killin',
  FK20: 'Crianlarich',
  FK21: 'Killin',
  // ── KA · Kilmarnock ──
  KA1: 'Kilmarnock, Bellfield, Shortlees',
  KA2: 'Kilmarnock, Crosshouse',
  KA3: 'Kilmarnock, Stewarton, Fenwick',
  KA4: 'Galston',
  KA5: 'Mauchline',
  KA6: 'Dalmellington, Patna',
  KA7: 'Ayr, Alloway',
  KA8: 'Ayr, Whitletts',
  KA9: 'Prestwick',
  KA10: 'Troon',
  KA11: 'Irvine, Girdle Toll',
  KA12: 'Irvine',
  KA13: 'Kilwinning',
  KA14: 'Beith',
  KA15: 'Beith',
  KA16: 'Newmilns',
  KA17: 'Darvel',
  KA18: 'Cumnock',
  KA19: 'Maybole',
  KA20: 'Stevenston',
  KA21: 'Saltcoats',
  KA22: 'Ardrossan',
  KA23: 'West Kilbride',
  KA24: 'Dalry',
  KA25: 'Kilbirnie',
  KA26: 'Girvan',
  KA27: 'Isle of Arran',
  KA28: 'Millport, Cumbrae',
  KA29: 'Largs',
  KA30: 'Largs',
  // ── KY · Kirkcaldy ──
  KY1: 'Kirkcaldy, Dysart',
  KY2: 'Kirkcaldy, Chapel',
  KY3: 'Burntisland, Kinghorn',
  KY4: 'Cowdenbeath, Kelty',
  KY5: 'Lochgelly',
  KY6: 'Glenrothes',
  KY7: 'Glenrothes',
  KY8: 'Leven, Methil',
  KY9: 'Elie, Earlsferry',
  KY10: 'Anstruther, Crail, Pittenweem',
  KY11: 'Dunfermline, Rosyth, Inverkeithing, Dalgety Bay',
  KY12: 'Dunfermline, Kincardine',
  KY13: 'Kinross',
  KY14: 'Cupar, Newburgh',
  KY15: 'Cupar',
  KY16: 'St Andrews',
  // ── ML · Motherwell ──
  ML1: 'Motherwell, Newarthill',
  ML2: 'Wishaw',
  ML3: 'Hamilton',
  ML4: 'Bellshill',
  ML5: 'Coatbridge',
  ML6: 'Airdrie',
  ML7: 'Shotts',
  ML8: 'Carluke',
  ML9: 'Larkhall',
  ML10: 'Strathaven',
  ML11: 'Lanark',
  ML12: 'Biggar',
  // ── PA · Paisley ──
  PA1: 'Paisley, Ralston',
  PA2: 'Paisley, Foxbar, Glenburn',
  PA3: 'Paisley, Ferguslie, Linwood',
  PA4: 'Renfrew',
  PA5: 'Johnstone',
  PA6: 'Houston',
  PA7: 'Bishopton',
  PA8: 'Erskine',
  PA9: 'Kilbarchan',
  PA10: 'Kilbarchan',
  PA11: 'Bridge of Weir',
  PA12: 'Lochwinnoch',
  PA13: 'Kilmacolm',
  PA14: 'Port Glasgow',
  PA15: 'Greenock',
  PA16: 'Greenock',
  PA17: 'Skelmorlie',
  PA18: 'Wemyss Bay',
  PA19: 'Gourock',
  PA20: 'Rothesay, Isle of Bute',
  PA21: 'Tighnabruaich',
  PA22: 'Colintraive',
  PA23: 'Dunoon',
  PA24: 'Cairndow',
  PA25: 'Cairndow',
  PA26: 'Cairndow',
  PA27: 'Cairndow',
  PA28: 'Campbeltown',
  PA29: 'Tarbert',
  PA30: 'Lochgilphead',
  PA31: 'Lochgilphead',
  PA32: 'Inveraray',
  PA33: 'Dalmally',
  PA34: 'Oban',
  PA35: 'Taynuilt',
  PA36: 'Bridge of Orchy',
  PA37: 'Oban, Connel',
  PA38: 'Appin',
  PA41: 'Isle of Gigha',
  PA42: 'Port Ellen, Islay',
  PA43: 'Bowmore, Islay',
  PA44: 'Bridgend, Islay',
  PA45: 'Port Askaig, Islay',
  PA46: 'Port Charlotte, Islay',
  PA47: 'Portnahaven, Islay',
  PA48: 'Bruichladdich, Islay',
  PA49: 'Isle of Islay',
  PA60: 'Isle of Jura',
  PA61: 'Isle of Colonsay',
  PA62: 'Isle of Mull',
  PA63: 'Isle of Mull',
  PA64: 'Isle of Mull',
  PA65: 'Craignure, Mull',
  PA66: 'Fionnphort, Mull',
  PA67: 'Bunessan, Mull',
  PA68: 'Isle of Mull',
  PA69: 'Isle of Mull',
  PA70: 'Isle of Mull',
  PA71: 'Isle of Mull',
  PA72: 'Isle of Mull',
  PA73: 'Isle of Mull',
  PA74: 'Isle of Mull',
  PA75: 'Tobermory, Mull',
  PA76: 'Isle of Iona',
  PA77: 'Isle of Tiree',
  PA78: 'Isle of Coll',
  PA80: 'Oban',
  // ── TD · Galashiels ──
  TD1: 'Galashiels',
  TD2: 'Lauder',
  TD3: 'Gordon',
  TD4: 'Earlston',
  TD5: 'Kelso',
  TD6: 'Melrose',
  TD7: 'Selkirk',
  TD8: 'Jedburgh',
  TD9: 'Hawick',
  TD10: 'Greenlaw',
  TD11: 'Duns',
  TD12: 'Coldstream',
  TD13: 'Cockburnspath',
  TD14: 'Eyemouth',
  TD15: 'Berwick-upon-Tweed',
};
