/** Localities per postcode district: AB, DD, IV, KW, PH, ZE, HS. Lead locality first. */
export const SCOTLAND_NORTH: Record<string, string> = {
  // ── AB · Aberdeen ──
  AB10: 'City centre, Ferryhill',
  AB11: 'Torry, Ferryhill, Harbour',
  AB12: 'Cove Bay, Portlethen, Nigg',
  AB13: 'Milltimber',
  AB14: 'Peterculter',
  AB15: 'West End, Mannofield, Cults, Hazlehead',
  AB16: 'Northfield, Mastrick, Sheddocksley',
  AB21: 'Dyce, Bucksburn, Newmachar',
  AB22: 'Bridge of Don, Danestone',
  AB23: 'Bridge of Don, Balmedie',
  AB24: 'Old Aberdeen, Kittybrewster, Woodside',
  AB25: 'Rosemount, Hilton, Kittybrewster',
  AB30: 'Laurencekirk',
  AB31: 'Banchory',
  AB32: 'Westhill',
  AB33: 'Alford',
  AB34: 'Aboyne',
  AB35: 'Ballater, Braemar',
  AB36: 'Strathdon',
  AB37: 'Ballindalloch',
  AB38: 'Aberlour',
  AB39: 'Stonehaven',
  AB41: 'Ellon',
  AB42: 'Peterhead',
  AB43: 'Fraserburgh',
  AB44: 'Macduff',
  AB45: 'Banff',
  AB51: 'Inverurie, Kintore, Oldmeldrum',
  AB52: 'Insch',
  AB53: 'Turriff',
  AB54: 'Huntly',
  AB55: 'Keith',
  AB56: 'Buckie',
  // ── DD · Dundee ──
  DD1: 'City centre, West End',
  DD2: 'Lochee, Menzieshill, Ninewells',
  DD3: 'Hilltown, Coldside, Kirkton',
  DD4: 'Stobswell, Craigie, Douglas',
  DD5: 'Broughty Ferry, Barnhill, Monifieth',
  DD6: 'Newport-on-Tay, Tayport',
  DD7: 'Carnoustie',
  DD8: 'Forfar, Kirriemuir',
  DD9: 'Brechin',
  DD10: 'Montrose',
  DD11: 'Arbroath',
  // ── IV · Inverness ──
  IV1: 'City centre, Crown',
  IV2: 'Inshes, Culloden, Milton of Leys',
  IV3: 'Dalneigh, Kinmylies, Clachnaharry',
  IV4: 'Beauly',
  IV5: 'Kirkhill',
  IV6: 'Muir of Ord',
  IV7: 'Conon Bridge',
  IV8: 'Munlochy',
  IV9: 'Avoch',
  IV10: 'Fortrose',
  IV11: 'Cromarty',
  IV12: 'Nairn',
  IV13: 'Tomatin',
  IV14: 'Strathpeffer',
  IV15: 'Dingwall',
  IV16: 'Evanton',
  IV17: 'Alness',
  IV18: 'Invergordon',
  IV19: 'Tain',
  IV20: 'Fearn',
  IV21: 'Gairloch',
  IV22: 'Achnasheen',
  IV23: 'Garve',
  IV24: 'Ardgay',
  IV25: 'Dornoch',
  IV26: 'Ullapool',
  IV27: 'Lairg',
  IV28: 'Rogart',
  IV30: 'Elgin',
  IV31: 'Lossiemouth',
  IV32: 'Fochabers',
  IV36: 'Forres',
  IV40: 'Kyle of Lochalsh',
  IV41: 'Kyleakin, Skye',
  IV42: 'Breakish, Skye',
  IV43: 'Isleornsay, Skye',
  IV44: 'Armadale, Skye',
  IV45: 'Ardvasar, Skye',
  IV46: 'Teangue, Skye',
  IV47: 'Carbost, Skye',
  IV48: 'Sconser, Skye',
  IV49: 'Broadford, Skye',
  IV51: 'Portree, Skye',
  IV52: 'Plockton',
  IV53: 'Strome Ferry',
  IV54: 'Lochcarron',
  IV55: 'Dunvegan, Skye',
  IV56: 'Struan, Skye',
  IV63: 'Drumnadrochit, Glenurquhart',
  // ── KW · Kirkwall ──
  KW1: 'Wick',
  KW2: 'Lybster',
  KW3: 'Lybster',
  KW5: 'Latheron',
  KW6: 'Dunbeath',
  KW7: 'Berriedale',
  KW8: 'Helmsdale',
  KW9: 'Brora',
  KW10: 'Golspie',
  KW11: 'Kinbrace',
  KW12: 'Halkirk',
  KW13: 'Forsinard',
  KW14: 'Thurso',
  KW15: 'Kirkwall, Orkney',
  KW16: 'Stromness, Orkney',
  KW17: 'Orkney Isles',
  // ── PH · Perth ──
  PH1: 'Perth, Scone, Bridge of Earn',
  PH2: 'Perth, Kinnoull, Abernethy',
  PH3: 'Auchterarder',
  PH4: 'Blackford',
  PH5: 'Crieff',
  PH6: 'Comrie',
  PH7: 'Crieff',
  PH8: 'Dunkeld',
  PH9: 'Pitlochry',
  PH10: 'Blairgowrie',
  PH11: 'Alyth',
  PH12: 'Meigle',
  PH13: 'Coupar Angus',
  PH14: 'Inchture, Errol',
  PH15: 'Aberfeldy',
  PH16: 'Pitlochry',
  PH17: 'Kinloch Rannoch',
  PH18: 'Blair Atholl',
  PH19: 'Dalwhinnie',
  PH20: 'Newtonmore',
  PH21: 'Kingussie',
  PH22: 'Aviemore',
  PH23: 'Carrbridge',
  PH24: 'Boat of Garten',
  PH25: 'Nethy Bridge',
  PH26: 'Grantown-on-Spey',
  PH30: 'Corrour',
  PH31: 'Roy Bridge',
  PH32: 'Fort Augustus',
  PH33: 'Fort William',
  PH34: 'Spean Bridge',
  PH35: 'Invergarry',
  PH36: 'Acharacle',
  PH37: 'Glenfinnan',
  PH38: 'Lochailort',
  PH39: 'Arisaig',
  PH40: 'Mallaig',
  PH41: 'Mallaig',
  PH42: 'Isle of Eigg',
  PH43: 'Isle of Rum',
  PH44: 'Isle of Canna',
  PH49: 'Ballachulish',
  PH50: 'Kinlochleven',
  // ── ZE · Shetland ──
  ZE1: 'Lerwick',
  ZE2: 'Shetland, Scalloway, Brae',
  ZE3: 'Shetland South, Sumburgh',
  // ── HS · Outer Hebrides ──
  HS1: 'Stornoway',
  HS2: 'Isle of Lewis',
  HS3: 'Isle of Harris',
  HS4: 'Scalpay',
  HS5: 'Leverburgh, Harris',
  HS6: 'North Uist',
  HS7: 'Benbecula',
  HS8: 'South Uist',
  HS9: 'Isle of Barra',
};
