/** Localities per postcode district: SN, SP, TA, TQ, TR. Lead locality first. */
export const SOUTH_WEST_B: Record<string, string> = {
  // ── SN · Swindon ──
  SN1: 'Swindon, Town centre, Old Town',
  SN2: 'Swindon, Gorse Hill, Rodbourne, Penhill',
  SN3: 'Swindon, Stratton, Covingham, Liden',
  SN4: 'Wroughton, Wootton Bassett',
  SN5: 'Swindon, West Swindon, Freshbrook, Toothill',
  SN6: 'Highworth, Cricklade, Shrivenham',
  SN7: 'Faringdon',
  SN8: 'Marlborough, Pewsey',
  SN9: 'Pewsey',
  SN10: 'Devizes',
  SN11: 'Calne',
  SN12: 'Melksham',
  SN13: 'Corsham',
  SN14: 'Chippenham, Castle Combe',
  SN15: 'Chippenham',
  SN16: 'Malmesbury',
  SN25: 'Swindon, Haydon Wick, Abbey Meads',
  SN26: 'Swindon, Blunsdon',
  // ── SP · Salisbury ──
  SP1: 'Salisbury, City centre, Bishopdown',
  SP2: 'Salisbury, Harnham, Bemerton, Wilton',
  SP3: 'Salisbury, Tisbury, Wilton',
  SP4: 'Amesbury, Durrington, Bulford',
  SP5: 'Salisbury, Downton, Alderbury',
  SP6: 'Fordingbridge',
  SP7: 'Shaftesbury',
  SP8: 'Gillingham',
  SP9: 'Tidworth',
  SP10: 'Andover',
  SP11: 'Andover, Ludgershall',
  // ── TA · Taunton ──
  TA1: 'Taunton, Town centre, Holway, Wilton',
  TA2: 'Taunton, Priorswood, Bathpool, Monkton Heathfield',
  TA3: 'Taunton, North Curry, Bishops Lydeard',
  TA4: 'Taunton, Wiveliscombe, Milverton',
  TA5: 'Bridgwater, Nether Stowey, Cannington',
  TA6: 'Bridgwater, Town centre',
  TA7: 'Bridgwater, Puriton, Woolavington',
  TA8: 'Burnham-on-Sea',
  TA9: 'Highbridge',
  TA10: 'Langport',
  TA11: 'Somerton',
  TA12: 'Martock',
  TA13: 'South Petherton',
  TA14: 'Stoke-sub-Hamdon',
  TA15: 'Montacute',
  TA16: 'Merriott',
  TA17: 'Hinton St George',
  TA18: 'Crewkerne',
  TA19: 'Ilminster',
  TA20: 'Chard',
  TA21: 'Wellington',
  TA22: 'Dulverton',
  TA23: 'Watchet',
  TA24: 'Minehead, Porlock, Dunster',
  // ── TQ · Torquay ──
  TQ1: 'Torquay, Town centre, Babbacombe, Ellacombe',
  TQ2: 'Torquay, Chelston, Cockington, Shiphay',
  TQ3: 'Paignton, Preston, Marldon',
  TQ4: 'Paignton, Goodrington, Roselands',
  TQ5: 'Brixham',
  TQ6: 'Dartmouth, Kingswear',
  TQ7: 'Kingsbridge, Salcombe',
  TQ8: 'Salcombe',
  TQ9: 'Totnes',
  TQ10: 'South Brent',
  TQ11: 'Buckfastleigh',
  TQ12: 'Newton Abbot, Kingsteignton',
  TQ13: 'Bovey Tracey, Ashburton, Chudleigh',
  TQ14: 'Teignmouth, Shaldon',
  // ── TR · Truro ──
  TR1: 'Truro, City centre',
  TR2: 'Truro, Probus, St Mawes',
  TR3: 'Truro, Perranarworthal, Feock',
  TR4: 'Truro, Threemilestone, Chacewater',
  TR5: 'St Agnes',
  TR6: 'Perranporth',
  TR7: 'Newquay',
  TR8: 'Newquay, St Columb, Crantock',
  TR9: 'St Columb',
  TR10: 'Penryn',
  TR11: 'Falmouth',
  TR12: 'Helston, The Lizard',
  TR13: 'Helston, Porthleven',
  TR14: 'Camborne',
  TR15: 'Redruth',
  TR16: 'Redruth, Lanner, Portreath',
  TR17: 'Marazion',
  TR18: 'Penzance, Newlyn',
  TR19: 'Penzance, St Just, Sennen',
  TR20: 'Penzance, Mousehole, St Buryan',
  TR21: 'Isles of Scilly, St Marys',
  TR22: 'Isles of Scilly, St Agnes',
  TR23: 'Isles of Scilly, Bryher',
  TR24: 'Isles of Scilly, Tresco',
  TR25: 'Isles of Scilly, St Martins',
  TR26: 'St Ives, Carbis Bay',
  TR27: 'Hayle',
};
