/** Localities per postcode district: PO, RG, RH, SL, SO, TN. Lead locality first. (BN, CT and OX are in the core table.) */
export const SOUTH_EAST_B: Record<string, string> = {
  // ── PO · Portsmouth ──
  PO1: 'Portsmouth, City centre, Old Portsmouth, Landport',
  PO2: 'Portsmouth, North End, Hilsea, Copnor',
  PO3: 'Portsmouth, Copnor, Baffins, Anchorage Park',
  PO4: 'Southsea, Eastney, Milton',
  PO5: 'Southsea, Somers Town',
  PO6: 'Cosham, Drayton, Farlington, Portchester',
  PO7: 'Waterlooville, Purbrook, Denmead',
  PO8: 'Waterlooville, Cowplain, Horndean, Clanfield',
  PO9: 'Havant, Bedhampton, Leigh Park',
  PO10: 'Emsworth, Westbourne',
  PO11: 'Hayling Island',
  PO12: 'Gosport, Alverstoke',
  PO13: 'Gosport, Lee-on-the-Solent, Bridgemary',
  PO14: 'Fareham, Stubbington, Titchfield',
  PO15: 'Fareham, Titchfield Common, Whiteley',
  PO16: 'Fareham, Town centre, Portchester',
  PO17: 'Fareham, Wickham',
  PO18: 'Chichester, Bosham, Westbourne',
  PO19: 'Chichester',
  PO20: 'Chichester, Selsey, The Witterings',
  PO21: 'Bognor Regis',
  PO22: 'Bognor Regis, Felpham, Middleton-on-Sea',
  PO30: 'Newport, Isle of Wight',
  PO31: 'Cowes',
  PO32: 'East Cowes',
  PO33: 'Ryde',
  PO34: 'Seaview',
  PO35: 'Bembridge',
  PO36: 'Sandown, Shanklin',
  PO37: 'Shanklin',
  PO38: 'Ventnor',
  PO39: 'Totland Bay',
  PO40: 'Freshwater',
  PO41: 'Yarmouth',
  // ── RG · Reading ──
  RG1: 'Reading, Town centre, Kings Road, Oxford Road',
  RG2: 'Reading, Whitley, Shinfield, Green Park',
  RG4: 'Caversham, Emmer Green, Sonning Common',
  RG5: 'Woodley',
  RG6: 'Earley, Lower Earley, University',
  RG7: 'Reading, Theale, Burghfield, Mortimer',
  RG8: 'Pangbourne, Goring, Streatley',
  RG9: 'Henley-on-Thames',
  RG10: 'Twyford, Wargrave',
  RG12: 'Bracknell, Town centre, Great Hollands',
  RG14: 'Newbury',
  RG17: 'Hungerford, Lambourn',
  RG18: 'Thatcham, Cold Ash',
  RG19: 'Thatcham, Greenham',
  RG20: 'Newbury, Kingsclere, Highclere',
  RG21: 'Basingstoke, Town centre',
  RG22: 'Basingstoke, Kempshott, Brighton Hill, Hatch Warren',
  RG23: 'Basingstoke, Oakley, Winklebury',
  RG24: 'Basingstoke, Chineham, Old Basing, Lychpit',
  RG25: 'Basingstoke, Overton, Dummer',
  RG26: 'Tadley, Baughurst',
  RG27: 'Hook, Hartley Wintney',
  RG28: 'Whitchurch',
  RG29: 'Odiham',
  RG30: 'Reading, Tilehurst, Southcote, Calcot',
  RG31: 'Tilehurst, Calcot, Purley on Thames',
  RG40: 'Wokingham',
  RG41: 'Wokingham, Winnersh',
  RG42: 'Bracknell, Binfield, Warfield',
  RG45: 'Crowthorne',
  // ── RH · Redhill ──
  RH1: 'Redhill, Merstham, Bletchingley',
  RH2: 'Reigate',
  RH3: 'Betchworth, Brockham',
  RH4: 'Dorking',
  RH5: 'Dorking, Holmwood, Capel',
  RH6: 'Horley, Gatwick',
  RH7: 'Lingfield',
  RH8: 'Oxted',
  RH9: 'Godstone',
  RH10: 'Crawley, Three Bridges, Pound Hill, Maidenbower',
  RH11: 'Crawley, Town centre, Bewbush, Broadfield',
  RH12: 'Horsham',
  RH13: 'Horsham, Southwater, Cowfold',
  RH14: 'Billingshurst',
  RH15: 'Burgess Hill',
  RH16: 'Haywards Heath',
  RH17: 'Haywards Heath, Cuckfield, Balcombe',
  RH18: 'Forest Row',
  RH19: 'East Grinstead',
  RH20: 'Pulborough, Storrington',
  // ── SL · Slough ──
  SL0: 'Iver, Richings Park',
  SL1: 'Slough, Town centre, Burnham, Cippenham',
  SL2: 'Slough, Farnham Royal, Stoke Poges',
  SL3: 'Slough, Langley, Colnbrook, Datchet',
  SL4: 'Windsor, Old Windsor',
  SL5: 'Ascot, Sunningdale',
  SL6: 'Maidenhead, Cookham, Bray',
  SL7: 'Marlow',
  SL8: 'Bourne End',
  SL9: 'Gerrards Cross, Chalfont St Peter',
  // ── SO · Southampton ──
  SO14: 'Southampton, City centre, Ocean Village, Bevois Valley',
  SO15: 'Southampton, Shirley, Freemantle, Polygon',
  SO16: 'Southampton, Bassett, Lordshill, Redbridge',
  SO17: 'Southampton, Portswood, Highfield, University',
  SO18: 'Southampton, Bitterne, Townhill Park, Harefield',
  SO19: 'Southampton, Sholing, Woolston, Weston',
  SO20: 'Stockbridge',
  SO21: 'Winchester, Twyford, Colden Common',
  SO22: 'Winchester, Weeke, Stanmore, Fulflood',
  SO23: 'Winchester, City centre, St Cross',
  SO24: 'Alresford',
  SO30: 'Hedge End, West End, Botley',
  SO31: 'Hamble, Warsash, Locks Heath, Netley',
  SO32: 'Bishops Waltham, Swanmore',
  SO40: 'Totton, Marchwood, Ashurst',
  SO41: 'Lymington, Milford on Sea, Sway',
  SO42: 'Brockenhurst, Beaulieu',
  SO43: 'Lyndhurst',
  SO45: 'Hythe, Dibden Purlieu, Fawley',
  SO50: 'Eastleigh, Bishopstoke, Fair Oak',
  SO51: 'Romsey',
  SO52: 'North Baddesley',
  SO53: 'Chandlers Ford',
  // ── TN · Tonbridge ──
  TN1: 'Tunbridge Wells, Town centre',
  TN2: 'Tunbridge Wells, Hawkenbury, Pembury, High Brooms',
  TN3: 'Tunbridge Wells, Langton Green, Groombridge',
  TN4: 'Tunbridge Wells, Southborough, St Johns, Rusthall',
  TN5: 'Wadhurst',
  TN6: 'Crowborough',
  TN7: 'Hartfield',
  TN8: 'Edenbridge',
  TN9: 'Tonbridge, Town centre',
  TN10: 'Tonbridge, Higham Wood, Trench',
  TN11: 'Tonbridge, Hildenborough, Hadlow',
  TN12: 'Paddock Wood, Marden, Staplehurst',
  TN13: 'Sevenoaks',
  TN14: 'Sevenoaks, Otford, Kemsing',
  TN15: 'Sevenoaks, Borough Green, Wrotham',
  TN16: 'Westerham, Biggin Hill',
  TN17: 'Cranbrook',
  TN18: 'Hawkhurst',
  TN19: 'Etchingham',
  TN20: 'Mayfield',
  TN21: 'Heathfield',
  TN22: 'Uckfield',
  TN23: 'Ashford, Town centre, Singleton',
  TN24: 'Ashford, Kennington, Willesborough',
  TN25: 'Ashford, Wye, Chilham',
  TN26: 'Ashford, Bethersden, Hamstreet',
  TN27: 'Ashford, Headcorn, Charing',
  TN28: 'New Romney',
  TN29: 'Romney Marsh, Dymchurch, Lydd',
  TN30: 'Tenterden',
  TN31: 'Rye',
  TN32: 'Robertsbridge',
  TN33: 'Battle',
  TN34: 'Hastings, Town centre, Old Town',
  TN35: 'Hastings, Ore, Fairlight',
  TN36: 'Winchelsea',
  TN37: 'St Leonards-on-Sea',
  TN38: 'St Leonards-on-Sea, Hollington',
  TN39: 'Bexhill-on-Sea',
  TN40: 'Bexhill-on-Sea',
};
