/** Localities per postcode district: BA, EX, PL. Lead locality first. (BH, BS, DT and GL are in the core table.) */
export const SOUTH_WEST_A: Record<string, string> = {
  // ── BA · Bath ──
  BA1: 'Bath, City centre, Lansdown, Larkhall, Weston',
  BA2: 'Bath, Widcombe, Oldfield Park, Combe Down, Bathwick',
  BA3: 'Radstock, Midsomer Norton',
  BA4: 'Shepton Mallet',
  BA5: 'Wells',
  BA6: 'Glastonbury, Street',
  BA7: 'Castle Cary',
  BA8: 'Templecombe',
  BA9: 'Wincanton',
  BA10: 'Bruton',
  BA11: 'Frome',
  BA12: 'Warminster',
  BA13: 'Westbury',
  BA14: 'Trowbridge',
  BA15: 'Bradford-on-Avon',
  BA16: 'Street',
  BA20: 'Yeovil, Town centre',
  BA21: 'Yeovil, Preston Plucknett, Mudford',
  BA22: 'Yeovil, Ilchester, Martock',
  // ── EX · Exeter ──
  EX1: 'Exeter, City centre, Heavitree, Whipton',
  EX2: 'Exeter, St Thomas, Wonford, Alphington',
  EX3: 'Topsham',
  EX4: 'Exeter, St Davids, Pennsylvania, Cowick',
  EX5: 'Exeter, Broadclyst, Cranbrook, Clyst St Mary',
  EX6: 'Exeter, Exminster, Kenton, Ide',
  EX7: 'Dawlish',
  EX8: 'Exmouth',
  EX9: 'Budleigh Salterton',
  EX10: 'Sidmouth',
  EX11: 'Ottery St Mary',
  EX12: 'Seaton',
  EX13: 'Axminster',
  EX14: 'Honiton',
  EX15: 'Cullompton',
  EX16: 'Tiverton',
  EX17: 'Crediton',
  EX18: 'Chulmleigh',
  EX19: 'Winkleigh',
  EX20: 'Okehampton',
  EX21: 'Beaworthy',
  EX22: 'Holsworthy',
  EX23: 'Bude',
  EX24: 'Colyton',
  EX31: 'Barnstaple, Town centre, Pilton',
  EX32: 'Barnstaple, Newport, Landkey',
  EX33: 'Braunton, Croyde',
  EX34: 'Ilfracombe, Woolacombe',
  EX35: 'Lynton, Lynmouth',
  EX36: 'South Molton',
  EX37: 'Umberleigh',
  EX38: 'Great Torrington',
  EX39: 'Bideford, Westward Ho, Appledore',
  // ── PL · Plymouth ──
  PL1: 'Plymouth, City centre, Stonehouse, Barbican, Hoe',
  PL2: 'Plymouth, Devonport, Stoke, Keyham',
  PL3: 'Plymouth, Mannamead, Peverell, Hartley',
  PL4: 'Plymouth, Mutley, Greenbank, Lipson',
  PL5: 'Plymouth, St Budeaux, Crownhill, Ernesettle',
  PL6: 'Plymouth, Derriford, Estover, Roborough',
  PL7: 'Plympton',
  PL8: 'Yealmpton, Newton Ferrers',
  PL9: 'Plymstock, Elburton, Wembury',
  PL10: 'Torpoint, Millbrook',
  PL11: 'Torpoint',
  PL12: 'Saltash',
  PL13: 'Looe',
  PL14: 'Liskeard',
  PL15: 'Launceston',
  PL16: 'Lifton',
  PL17: 'Callington',
  PL18: 'Gunnislake',
  PL19: 'Tavistock',
  PL20: 'Yelverton, Princetown',
  PL21: 'Ivybridge',
  PL22: 'Lostwithiel',
  PL23: 'Fowey',
  PL24: 'Par',
  PL25: 'St Austell',
  PL26: 'St Austell, Mevagissey',
  PL27: 'Wadebridge, Rock, Polzeath',
  PL28: 'Padstow',
  PL29: 'Port Isaac',
  PL30: 'Bodmin, Lanivet',
  PL31: 'Bodmin',
  PL32: 'Camelford',
  PL33: 'Delabole',
  PL34: 'Tintagel',
  PL35: 'Boscastle',
};
