/** Localities per postcode district: DA, GU, HP, ME, MK. Lead locality first. */
export const SOUTH_EAST_A: Record<string, string> = {
  // ── DA · Dartford ──
  DA1: 'Dartford, Town centre, Crayford',
  DA2: 'Dartford, Stone, Bean, Darenth',
  DA3: 'Longfield, Hartley, New Ash Green',
  DA4: 'Farningham, Eynsford, South Darenth',
  DA5: 'Bexley',
  DA6: 'Bexleyheath',
  DA7: 'Bexleyheath, Barnehurst',
  DA8: 'Erith',
  DA9: 'Greenhithe',
  DA10: 'Swanscombe',
  DA11: 'Gravesend, Northfleet',
  DA12: 'Gravesend, Chalk, Shorne',
  DA13: 'Meopham',
  DA14: 'Sidcup',
  DA15: 'Sidcup, Blackfen',
  DA16: 'Welling',
  DA17: 'Belvedere',
  DA18: 'Erith, Belvedere Marshes',
  // ── GU · Guildford ──
  GU1: 'Guildford, Town centre, Burpham, Merrow',
  GU2: 'Guildford, Park Barn, Onslow Village, University',
  GU3: 'Guildford, Worplesdon, Normandy',
  GU4: 'Guildford, Shalford, Chilworth, Jacobs Well',
  GU5: 'Bramley, Shamley Green',
  GU6: 'Cranleigh',
  GU7: 'Godalming',
  GU8: 'Godalming, Milford, Witley',
  GU9: 'Farnham, Town centre, Hale',
  GU10: 'Farnham, Wrecclesham, Tilford',
  GU11: 'Aldershot',
  GU12: 'Aldershot, Ash, Ash Vale',
  GU14: 'Farnborough',
  GU15: 'Camberley',
  GU16: 'Frimley, Frimley Green, Deepcut',
  GU17: 'Blackwater, Hawley',
  GU18: 'Lightwater',
  GU19: 'Bagshot',
  GU20: 'Windlesham',
  GU21: 'Woking, Town centre, Knaphill, Goldsworth Park',
  GU22: 'Woking, Old Woking, Hook Heath, Pyrford',
  GU23: 'Ripley, Send',
  GU24: 'Chobham, Bisley, Pirbright',
  GU25: 'Virginia Water',
  GU26: 'Hindhead, Grayshott',
  GU27: 'Haslemere',
  GU28: 'Petworth',
  GU29: 'Midhurst',
  GU30: 'Liphook',
  GU31: 'Petersfield',
  GU32: 'Petersfield, East Meon',
  GU33: 'Liss',
  GU34: 'Alton',
  GU35: 'Bordon, Headley',
  GU46: 'Yateley',
  GU47: 'Sandhurst, College Town',
  GU51: 'Fleet',
  GU52: 'Fleet, Church Crookham',
  // ── HP · Hemel Hempstead ──
  HP1: 'Hemel Hempstead, Town centre, Boxmoor, Gadebridge',
  HP2: 'Hemel Hempstead, Adeyfield, Grovehill, Woodhall Farm',
  HP3: 'Hemel Hempstead, Apsley, Leverstock Green, Bovingdon',
  HP4: 'Berkhamsted',
  HP5: 'Chesham',
  HP6: 'Amersham',
  HP7: 'Amersham, Little Chalfont',
  HP8: 'Chalfont St Giles',
  HP9: 'Beaconsfield',
  HP10: 'High Wycombe, Loudwater, Flackwell Heath',
  HP11: 'High Wycombe, Town centre',
  HP12: 'High Wycombe, Sands, Booker',
  HP13: 'High Wycombe, Downley, Terriers, Totteridge',
  HP14: 'High Wycombe, Hazlemere, Stokenchurch',
  HP15: 'High Wycombe, Hazlemere, Holmer Green',
  HP16: 'Great Missenden',
  HP17: 'Aylesbury, Haddenham',
  HP18: 'Aylesbury, Waddesdon, Brill',
  HP19: 'Aylesbury, Fairford Leys, Watermead',
  HP20: 'Aylesbury, Town centre, Bierton',
  HP21: 'Aylesbury, Walton, Stoke Mandeville',
  HP22: 'Aylesbury, Wendover, Weston Turville',
  HP23: 'Tring',
  HP27: 'Princes Risborough',
  // ── ME · Medway ──
  ME1: 'Rochester, Town centre, Borstal',
  ME2: 'Strood, Frindsbury, Cliffe',
  ME3: 'Hoo, Cliffe, Isle of Grain',
  ME4: 'Chatham, Town centre, Luton',
  ME5: 'Chatham, Walderslade, Lordswood, Blue Bell Hill',
  ME6: 'Snodland',
  ME7: 'Gillingham, Town centre, Brompton',
  ME8: 'Rainham, Twydall, Parkwood',
  ME9: 'Sittingbourne, Newington, Iwade',
  ME10: 'Sittingbourne, Town centre, Kemsley',
  ME11: 'Queenborough',
  ME12: 'Sheerness, Minster, Leysdown',
  ME13: 'Faversham',
  ME14: 'Maidstone, Town centre, Penenden Heath, Bearsted',
  ME15: 'Maidstone, Shepway, Loose, Tovil',
  ME16: 'Maidstone, Barming, Allington, Fant',
  ME17: 'Maidstone, Coxheath, Lenham, Harrietsham',
  ME18: 'Maidstone, West Farleigh, Yalding',
  ME19: 'West Malling, Kings Hill, Leybourne',
  ME20: 'Aylesford, Larkfield, Ditton',
  // ── MK · Milton Keynes ──
  MK1: 'Bletchley, Denbigh, Mount Farm',
  MK2: 'Bletchley, Water Eaton',
  MK3: 'Bletchley, Far Bletchley, West Bletchley',
  MK4: 'Emerson Valley, Furzton, Westcroft, Tattenhoe',
  MK5: 'Shenley Brook End, Loughton, Grange Farm',
  MK6: 'Netherfield, Coffee Hall, Beanhill, Eaglestone',
  MK7: 'Walton, Wavendon, Kents Hill, Caldecotte',
  MK8: 'Great Holm, Two Mile Ash, Crownhill',
  MK9: 'Central Milton Keynes',
  MK10: 'Broughton, Middleton, Monkston, Kingston',
  MK11: 'Stony Stratford, Fullers Slade',
  MK12: 'Wolverton, Greenleys, Stacey Bushes',
  MK13: 'Bradwell, Heelands, Bancroft, New Bradwell',
  MK14: 'Stantonbury, Great Linford, Downhead Park',
  MK15: 'Willen, Pennyland, Downs Barn, Tongwell',
  MK16: 'Newport Pagnell',
  MK17: 'Woburn Sands, Bow Brickhill, Wavendon',
  MK18: 'Buckingham, Winslow',
  MK19: 'Deanshanger, Hanslope, Castlethorpe',
  MK40: 'Bedford, Town centre, De Parys',
  MK41: 'Bedford, Goldington, Putnoe, Brickhill',
  MK42: 'Bedford, Kempston, Elstow',
  MK43: 'Bedford, Cranfield, Wootton, Bromham',
  MK44: 'Bedford, Wilden, Sharnbrook',
  MK45: 'Flitwick, Ampthill, Barton-le-Clay',
  MK46: 'Olney',
};
