/** Localities per postcode district: LD, LL, NP. Lead locality first. (CF and SA are in the core table.) */
export const WALES: Record<string, string> = {
  // ── LD · Llandrindod Wells ──
  LD1: 'Llandrindod Wells',
  LD2: 'Builth Wells',
  LD3: 'Brecon',
  LD4: 'Llangammarch Wells',
  LD5: 'Llanwrtyd Wells',
  LD6: 'Rhayader',
  LD7: 'Knighton',
  LD8: 'Presteigne',
  // ── LL · Llandudno ──
  LL11: 'Wrexham, Rhosddu, Brymbo',
  LL12: 'Wrexham, Gresford, Rossett',
  LL13: 'Wrexham, Rhostyllen, Marchwiel',
  LL14: 'Ruabon, Rhosllanerchrugog, Chirk',
  LL15: 'Ruthin',
  LL16: 'Denbigh',
  LL17: 'St Asaph',
  LL18: 'Rhyl, Rhuddlan',
  LL19: 'Prestatyn',
  LL20: 'Llangollen',
  LL21: 'Corwen',
  LL22: 'Abergele',
  LL23: 'Bala',
  LL24: 'Betws-y-Coed',
  LL25: 'Dolwyddelan',
  LL26: 'Llanrwst',
  LL27: 'Trefriw',
  LL28: 'Colwyn Bay, Rhos-on-Sea',
  LL29: 'Colwyn Bay, Old Colwyn',
  LL30: 'Llandudno',
  LL31: 'Llandudno Junction, Deganwy',
  LL32: 'Conwy',
  LL33: 'Llanfairfechan',
  LL34: 'Penmaenmawr',
  LL35: 'Aberdyfi',
  LL36: 'Tywyn',
  LL37: 'Llwyngwril',
  LL38: 'Fairbourne',
  LL39: 'Arthog',
  LL40: 'Dolgellau',
  LL41: 'Blaenau Ffestiniog',
  LL42: 'Barmouth',
  LL43: 'Talybont',
  LL44: 'Dyffryn Ardudwy',
  LL45: 'Llanbedr',
  LL46: 'Harlech',
  LL47: 'Talsarnau',
  LL48: 'Penrhyndeudraeth',
  LL49: 'Porthmadog',
  LL51: 'Garndolbenmaen',
  LL52: 'Criccieth',
  LL53: 'Pwllheli, Abersoch, Nefyn',
  LL54: 'Caernarfon, Penygroes',
  LL55: 'Caernarfon, Llanberis',
  LL56: 'Y Felinheli',
  LL57: 'Bangor, Bethesda',
  LL58: 'Beaumaris',
  LL59: 'Menai Bridge',
  LL60: 'Gaerwen',
  LL61: 'Llanfairpwllgwyngyll',
  LL62: 'Bodorgan',
  LL63: 'Ty Croes',
  LL64: 'Rhosneigr',
  LL65: 'Holyhead, Valley',
  LL66: 'Rhosgoch',
  LL67: 'Cemaes Bay',
  LL68: 'Amlwch',
  LL69: 'Penysarn',
  LL70: 'Dulas',
  LL71: 'Llanerchymedd',
  LL72: 'Moelfre',
  LL73: 'Marianglas',
  LL74: 'Tynygongl, Benllech',
  LL75: 'Pentraeth',
  LL76: 'Llanbedrgoch',
  LL77: 'Llangefni',
  LL78: 'Brynteg',
  // ── NP · Newport ──
  NP4: 'Pontypool, Abersychan',
  NP7: 'Abergavenny',
  NP8: 'Crickhowell',
  NP10: 'Rogerstone, Bassaleg, Duffryn',
  NP11: 'Risca, Newbridge, Crosskeys',
  NP12: 'Blackwood',
  NP13: 'Abertillery',
  NP15: 'Usk',
  NP16: 'Chepstow',
  NP18: 'Caerleon, Langstone',
  NP19: 'Newport, Maindee, St Julians, Lliswerry',
  NP20: 'Newport, City centre, Gaer, Malpas',
  NP22: 'Tredegar',
  NP23: 'Ebbw Vale, Brynmawr',
  NP24: 'New Tredegar',
  NP25: 'Monmouth',
  NP26: 'Caldicot, Magor',
  NP44: 'Cwmbran',
};
