/** Localities per postcode district: CV, DY, HR, ST. Lead locality first. (B is in the core table.) */
export const WEST_MIDLANDS_A: Record<string, string> = {
  // ── CV · Coventry ──
  CV1: 'Coventry, City centre, Hillfields',
  CV2: 'Coventry, Walsgrave, Wyken, Stoke',
  CV3: 'Coventry, Binley, Cheylesmore, Stivichall, Whitley',
  CV4: 'Coventry, Canley, Tile Hill, Westwood Heath',
  CV5: 'Coventry, Earlsdon, Chapelfields, Allesley, Coundon',
  CV6: 'Coventry, Radford, Holbrooks, Longford, Foleshill',
  CV7: 'Bedworth, Exhall, Keresley, Meriden',
  CV8: 'Kenilworth, Ryton-on-Dunsmore',
  CV9: 'Atherstone',
  CV10: 'Nuneaton, Stockingford, Camp Hill',
  CV11: 'Nuneaton, Town centre, Attleborough',
  CV12: 'Bedworth, Bulkington',
  CV13: 'Market Bosworth',
  CV21: 'Rugby, Town centre, Brownsover',
  CV22: 'Rugby, Bilton, Cawston',
  CV23: 'Rugby, Long Lawford, Dunchurch',
  CV31: 'Leamington Spa, Whitnash, Sydenham',
  CV32: 'Leamington Spa, Lillington, Cubbington',
  CV33: 'Leamington Spa, Harbury, Bishops Tachbrook',
  CV34: 'Warwick',
  CV35: 'Warwick, Wellesbourne, Kineton',
  CV36: 'Shipston-on-Stour',
  CV37: 'Stratford-upon-Avon',
  CV47: 'Southam',
  // ── DY · Dudley ──
  DY1: 'Dudley, Town centre, Woodsetton',
  DY2: 'Dudley, Netherton, Holly Hall',
  DY3: 'Sedgley, Gornal, Himley',
  DY4: 'Tipton',
  DY5: 'Brierley Hill, Quarry Bank, Pensnett',
  DY6: 'Kingswinford, Wall Heath',
  DY7: 'Kinver, Stourton',
  DY8: 'Stourbridge, Wordsley, Amblecote',
  DY9: 'Stourbridge, Lye, Pedmore, Hagley',
  DY10: 'Kidderminster, Town centre, Hoo Brook',
  DY11: 'Kidderminster, Bewdley Road, Wolverley',
  DY12: 'Bewdley',
  DY13: 'Stourport-on-Severn',
  DY14: 'Cleobury Mortimer',
  // ── HR · Hereford ──
  HR1: 'Hereford, City centre, Tupsley, Hampton Park',
  HR2: 'Hereford, Belmont, Redhill, Kingstone',
  HR3: 'Hay-on-Wye, Kington',
  HR4: 'Hereford, Whitecross, Kings Acre, Credenhill',
  HR5: 'Kington',
  HR6: 'Leominster',
  HR7: 'Bromyard',
  HR8: 'Ledbury',
  HR9: 'Ross-on-Wye',
  // ── ST · Stoke-on-Trent ──
  ST1: 'Hanley, Northwood, Shelton',
  ST2: 'Bucknall, Abbey Hulton, Bentilee',
  ST3: 'Longton, Meir, Blurton, Weston Coyney',
  ST4: 'Stoke, Penkhull, Trentham, Hartshill',
  ST5: 'Newcastle-under-Lyme, Keele, Clayton',
  ST6: 'Burslem, Tunstall, Smallthorne',
  ST7: 'Kidsgrove, Alsager, Talke',
  ST8: 'Biddulph',
  ST9: 'Endon, Stockton Brook',
  ST10: 'Cheadle, Alton',
  ST11: 'Blythe Bridge',
  ST12: 'Barlaston',
  ST13: 'Leek',
  ST14: 'Uttoxeter',
  ST15: 'Stone',
  ST16: 'Stafford, Town centre, Doxey',
  ST17: 'Stafford, Weeping Cross, Wildwood, Baswich',
  ST18: 'Stafford, Great Haywood, Hixon',
  ST19: 'Penkridge',
  ST20: 'Gnosall',
  ST21: 'Eccleshall',
};
