/** Localities per postcode district: SY, TF, WR, WS, WV. Lead locality first. */
export const WEST_MIDLANDS_B: Record<string, string> = {
  // ── SY · Shrewsbury ──
  SY1: 'Shrewsbury, Town centre, Castlefields, Harlescott',
  SY2: 'Shrewsbury, Monkmoor, Belle Vue, Sutton',
  SY3: 'Shrewsbury, Meole Brace, Bayston Hill, Copthorne',
  SY4: 'Shrewsbury, Baschurch, Wem, Shawbury',
  SY5: 'Shrewsbury, Pontesbury, Minsterley',
  SY6: 'Church Stretton',
  SY7: 'Craven Arms, Bishops Castle',
  SY8: 'Ludlow',
  SY9: 'Bishops Castle',
  SY10: 'Oswestry, Llansilin',
  SY11: 'Oswestry',
  SY12: 'Ellesmere',
  SY13: 'Whitchurch',
  SY14: 'Malpas',
  SY15: 'Montgomery',
  SY16: 'Newtown',
  SY17: 'Llandinam, Caersws',
  SY18: 'Llanidloes',
  SY19: 'Llanbrynmair',
  SY20: 'Machynlleth',
  SY21: 'Welshpool',
  SY22: 'Llanfyllin, Meifod',
  SY23: 'Aberystwyth',
  SY24: 'Bow Street, Borth',
  SY25: 'Tregaron',
  // ── TF · Telford ──
  TF1: 'Telford, Wellington, Hadley, Leegomery',
  TF2: 'Telford, Oakengates, Priorslee, Donnington',
  TF3: 'Telford, Town centre, Stirchley, Randlay',
  TF4: 'Telford, Dawley, Lawley, Malinslee',
  TF5: 'Telford, Admaston, Bratton',
  TF6: 'Telford, High Ercall, Rodington',
  TF7: 'Telford, Madeley, Sutton Hill, Woodside',
  TF8: 'Ironbridge, Coalbrookdale',
  TF9: 'Market Drayton',
  TF10: 'Newport, Edgmond',
  TF11: 'Shifnal',
  TF12: 'Broseley',
  TF13: 'Much Wenlock',
  // ── WR · Worcester ──
  WR1: 'Worcester, City centre, Barbourne',
  WR2: 'Worcester, St Johns, Dines Green, Rushwick',
  WR3: 'Worcester, Claines, Northwick, Fernhill Heath',
  WR4: 'Worcester, Warndon, Blackpole, Tolladine',
  WR5: 'Worcester, Battenhall, Red Hill, Norton',
  WR6: 'Martley, Ombersley, Great Witley',
  WR7: 'Flyford Flavell, Upton Snodsbury',
  WR8: 'Upton upon Severn',
  WR9: 'Droitwich Spa',
  WR10: 'Pershore',
  WR11: 'Evesham',
  WR12: 'Broadway',
  WR13: 'Malvern, Colwall',
  WR14: 'Malvern, Great Malvern, Malvern Link',
  WR15: 'Tenbury Wells',
  // ── WS · Walsall ──
  WS1: 'Walsall, Town centre, Caldmore',
  WS2: 'Walsall, Pleck, Birchills, Bentley',
  WS3: 'Bloxwich, Pelsall',
  WS4: 'Walsall, Rushall, Shelfield',
  WS5: 'Walsall, Park Hall, Yew Tree',
  WS6: 'Cheslyn Hay, Great Wyrley',
  WS7: 'Burntwood, Chase Terrace',
  WS8: 'Brownhills, Walsall Wood',
  WS9: 'Aldridge, Walsall Wood',
  WS10: 'Wednesbury, Darlaston',
  WS11: 'Cannock, Norton Canes',
  WS12: 'Hednesford, Heath Hayes',
  WS13: 'Lichfield, City centre, Boley Park',
  WS14: 'Lichfield, Shenstone, Whittington',
  WS15: 'Rugeley',
  // ── WV · Wolverhampton ──
  WV1: 'Wolverhampton, City centre, Eastfield',
  WV2: 'Wolverhampton, Blakenhall, All Saints',
  WV3: 'Wolverhampton, Compton, Merridale, Finchfield',
  WV4: 'Wolverhampton, Penn, Goldthorn Park, Parkfield',
  WV5: 'Wombourne',
  WV6: 'Wolverhampton, Tettenhall, Perton, Compton',
  WV7: 'Albrighton',
  WV8: 'Codsall, Bilbrook',
  WV9: 'Pendeford',
  WV10: 'Wolverhampton, Bushbury, Fordhouses, Low Hill',
  WV11: 'Wednesfield, Ashmore Park',
  WV12: 'Willenhall, New Invention',
  WV13: 'Willenhall',
  WV14: 'Bilston, Bradley',
  WV15: 'Bridgnorth, Low Town',
  WV16: 'Bridgnorth, High Town',
};
