/** Localities per postcode district: DN, HD, HX, WF. Lead locality first. (BD, HG, HU, LS, S and YO are in the core table.) */
export const YORKSHIRE: Record<string, string> = {
  // ── DN · Doncaster ──
  DN1: 'Doncaster, Town centre',
  DN2: 'Doncaster, Wheatley, Intake',
  DN3: 'Armthorpe, Edenthorpe, Branton',
  DN4: 'Doncaster, Bessacarr, Balby, Hyde Park',
  DN5: 'Bentley, Scawthorpe, Sprotbrough',
  DN6: 'Askern, Adwick-le-Street, Carcroft',
  DN7: 'Hatfield, Stainforth, Dunscroft',
  DN8: 'Thorne, Moorends',
  DN9: 'Epworth, Haxey, Finningley',
  DN10: 'Bawtry, Misterton',
  DN11: 'Rossington, Tickhill, Harworth',
  DN12: 'Conisbrough, Denaby',
  DN14: 'Goole, Howden, Snaith',
  DN15: 'Scunthorpe, Town centre, Burton upon Stather',
  DN16: 'Scunthorpe, Ashby, Bottesford',
  DN17: 'Scunthorpe, Crowle, Epworth',
  DN18: 'Barton-upon-Humber',
  DN19: 'Barrow upon Humber',
  DN20: 'Brigg',
  DN21: 'Gainsborough',
  DN22: 'Retford',
  DN31: 'Grimsby, Town centre',
  DN32: 'Grimsby, East Marsh',
  DN33: 'Grimsby, Scartho',
  DN34: 'Grimsby, Nunsthorpe, Laceby',
  DN35: 'Cleethorpes',
  DN36: 'Humberston, New Waltham, Holton-le-Clay',
  DN37: 'Waltham, Laceby, Great Coates',
  DN38: 'Barnetby',
  DN39: 'Ulceby',
  DN40: 'Immingham',
  DN41: 'Stallingborough, Keelby',
  // ── HD · Huddersfield ──
  HD1: 'Huddersfield, Town centre, Marsh',
  HD2: 'Huddersfield, Fartown, Birkby, Fixby',
  HD3: 'Huddersfield, Lindley, Oakes, Salendine Nook',
  HD4: 'Huddersfield, Newsome, Lockwood, Netherton',
  HD5: 'Huddersfield, Almondbury, Kirkheaton, Dalton',
  HD6: 'Brighouse, Rastrick',
  HD7: 'Golcar, Slaithwaite, Marsden',
  HD8: 'Skelmanthorpe, Kirkburton, Denby Dale',
  HD9: 'Holmfirth, Honley, Meltham',
  // ── HX · Halifax ──
  HX1: 'Halifax, Town centre, King Cross',
  HX2: 'Halifax, Illingworth, Ovenden, Mixenden',
  HX3: 'Halifax, Hipperholme, Northowram, Southowram',
  HX4: 'Greetland, Stainland, Barkisland',
  HX5: 'Elland',
  HX6: 'Sowerby Bridge, Ripponden',
  HX7: 'Hebden Bridge, Mytholmroyd',
  // ── WF · Wakefield ──
  WF1: 'Wakefield, City centre, Eastmoor, Outwood',
  WF2: 'Wakefield, Sandal, Kettlethorpe, Alverthorpe',
  WF3: 'Lofthouse, Stanley, East Ardsley',
  WF4: 'Horbury, Crigglestone, Netherton',
  WF5: 'Ossett',
  WF6: 'Normanton, Altofts',
  WF7: 'Featherstone, Ackworth',
  WF8: 'Pontefract',
  WF9: 'South Elmsall, Hemsworth, South Kirkby',
  WF10: 'Castleford, Allerton Bywater',
  WF11: 'Knottingley',
  WF12: 'Dewsbury, Thornhill, Savile Town',
  WF13: 'Dewsbury, Ravensthorpe',
  WF14: 'Mirfield',
  WF15: 'Liversedge',
  WF16: 'Heckmondwike',
  WF17: 'Batley, Birstall',
};
